mathics/builtin/arithmetic.py
mathics/builtin/attributes.py
mathics/builtin/calculus.py
mathics/builtin/diffeqns.py
mathics/builtin/files.py
mathics/builtin/graphics.py
mathics/doc/doc.py
mathics/doc/utils.py
mathics/web/urls.py

This is a fix for some doc issues introduced in the context branch. Adding `$Context` exposed a problem where dollar signs weren't significant in doc links. I've tried to fix this but I'm definitely not a Django expert, so it'd be good to know if this isn't right.
I plan to add more stuff to this soon to document some undocumented symbols that came in with the context branch, but it'd be good to know if what I've got so far is along the right lines.

Various fixes for docs

---

setup.py

I light of the feedback provided in #240, I've removed argparse as a dependency unless running Python2.6.

argparse only required for 2.6 #240

---

tox.ini

You're no doubt familiar with the way Travis runs the test suite across
various versions of Python, with versions versions of sympy
Tox gives similar functionality on your development machine.
If you just run tox, it will run the tests defined in each environment -
in this case, there are 6 versions of python tested against 4 versions
of sympy each.
If you just want to test (for instance) py27 with sympy-master, you can
use `tox -e py26-sympymaster`
You can get a full list of all available environments with `tox -l`
Each combination will run in its own virtualenv; these are under .tox in
the project root.
I think I've managed to capture most of the logic expressed in the
travis.yml in this file

Add a basic tox setup

---

mathics/builtin/numeric.py
mathics/core/numbers.py

This is another small bug along the lines of the log(0) IntegerDigits one

Fix crashes in BaseForm with zero values or out-of-range bases

---

index.html

Maybe you guys should find a way to make use of mathics.github.io rather than mathics.github.io/Mathics too?

Fix gh-pages index repo link

---

mathics/builtin/assignment.py

Reverts mathics/Mathics#286
In light of #307 I've realised this breaks `Quit[]`
ping @mmatera

Revert "Adding the regular functionality of Quit"

---

mathics/builtin/lists.py

`map(None, iter1, iter2)` appears to be dumped in python3.
This commit cleans up some `Riffle` edge cases.

Riffle fixes

---

setup.py

These directories aren't python packages, rather we should treat them as package data for the `mathics` package.

cleaup data,autoload,packages in setup.py

---

mathics/web/media/js/inout.js

in the web interface i had trouble loading a worksheet that contained unevaluated cells.
the sheet up to and including the first unevaluated cell would load, the remainder would be
missing.
the save command saves unevaluated cells ok, the load command should also load them. 
the small change within this pull request fixes this.
but i'm not a javascript expert!  checking against undefined may not be the best way
of doing the check.

load unevaluated cells

---

mathics/builtin/assignment.py
mathics/builtin/scoping.py

Hit this trying to get the ```KnotTheory` ``` package working in Mathics.
```mathematica
Begin["`System`"]
```
was returning ``` `System` ```, not the fully qualified ```Global`System```. It turns out `$Context` was being set first correctly to ```Global`System` ``` and reset then to ``` `System` ```.
@bnjones does this fix look right to you?

Global system bug

---

mathics/builtin/numbertheory.py

Python's built-in `pow` function can already do modular exponentiation, so we don't need to compute the power and reduce. The only extra part here is to handle errors SymPy raises if it can't find the multiplicative inverse.

Avoid computing x^y in PowerMod[x, y, m]

---

mathics/builtin/scoping.py

Fixes `Names["@"]` being nonempty at startup or after a `Quit[]`

Fix Begin/BeginPackage leaking user-visible symbols

---

mathics/builtin/patterns.py
mathics/builtin/strings.py

Implements some string expression enhancements.
The main idea here is to represent the various string expression components as regex or combinations of regex; see `to_regex`.
I initially tried to workaround some strange behaviour in `re.split` but ended up rewriting it; see `mathics_split`.
TODO:
Tests/docs for:
Not implemented:
- `Shortest` and `Longest`
- `StringCases`

String expression

---

mathics/core/evaluation.py
mathics/settings.py

Images in particular are too large to store in the DB (on public web servers), but locally it's probably okay to store them.

add MAX_STORED_SIZE setting

---

mathics/core/expression.py

Before this change:
Timing[Length[Table[i, {i, 1, 10000}]]]
{ 11.398169 , 10000 }
After this change:
Timing[Length[Table[i, {i, 1, 10000}]]]
{ 8.621232000000001 , 10000 }
The gain is related to the __eq__ implementation of Expression using get_sort_key(), which seems to be relatively slow for Symbols.

small change that yields a 25% performance gain

---

mathics/builtin/comparison.py

small bug I found:
`"abc" == Null`  was crashing but`Null == "abc"` was okay
`to_sympy` converts the `String` to `str` but since `str` is not a true sympy object `is_number` isn't implemented.

fix symbol string comparison bug

---

mathics/builtin/calculus.py

Use `Function` with named args, avoiding problems if the pattern variables contain slots

Fix for issue #375: avoid slots in rule handling D[{...}, ...]

---

mathics/builtin/system.py

Otherwise various functions return ``System`$Failed`` but ``$Failed`` evaluates to ``Global`$Failed``on input, causing problems like:
```
In[1]:= Get["nonexistent"] === $Failed
: Cannot open nonexistent.
Out[1]= False
```

Predefine and document $Aborted and $Failed

---

mathics/core/expression.py
mathics/core/rules.py

Mathics currently reevaluates variable values (i.e. values of symbols set via Set[]) every time they're accessed.
This can lead to some worrisome performance (and it gets worse for even longer lists):
`x=Range[10000]; Timing[First[x]]`
`{0.2507470000000005,1}`
This PR fixes this by not rebuilding expressions if no var is replaced. That way, the original expression's is_evaluated attribute does not get reset, and the expression is thus not reevaluated when Expression.evaluate() gets called for it later on. With change in PR:
`x=Range[10000]; Timing[First[x]]`
`{0.08288399999999996,1}`

No reevaluation of evaluated values

---

.travis.yml
mathics/builtin/numpy_utils.py
mathics/builtin/randomnumbers.py
setup.py

Adds RandomChoice[] and RandomSample[]. These two need numpy installed.
I rewired RandomInteger[] et al. to numpy (if it's installed), as there should be one consistent random number provider for the system that attaches to one random generator state, which can be set, reset, etc.. Starting to have different random generator states for e.g. RandomInteger[] and RandomChoice[] (and ImageRandom[] and others in the future for that matter) would surely spell disaster. So if numpy is available, everything is based on the numpy generator now.
If numpy is not installed (e.g. for PyPy) the implementation falls back and is equivalent in its results to the old implementation. Then, however, RandomChoice[] and RandomSample[] are not available. They could be added through adding a python only …

RandomChoice[] and RandomSample[]

---

mathics/builtin/__init__.py
mathics/builtin/arithmetic.py
mathics/builtin/base.py
mathics/builtin/calculus.py
mathics/core/convert.py
mathics/core/expression.py
test/test_convert.py

SymPy exposes separate `gamma()` and `uppergamma()` functions, whereas in Mathematica `Gamma[z]` is the gamma function and `Gamma[z, x]` is the upper incomplete gamma function.
Add support for `Gamma[z, x]` plus plumbing for mapping multiple SymPy functions onto one builtin. Right now I think it's just this one function that needs this kind of treatment, but it'd easy to factor out if there are more.

Improve support for gamma functions

---

mathics/builtin/arithmetic.py

This code dates back to the original version of Mathics in 2011 (a77c08e66e6103d28af3c09e69e0d857600c10da),  but it's no longer needed.

cleanup Factorial

---

mathics/builtin/algebra.py
mathics/builtin/arithmetic.py
mathics/builtin/base.py
mathics/builtin/calculus.py
mathics/builtin/combinatorial.py
mathics/builtin/comparison.py
mathics/builtin/integer.py
mathics/builtin/linalg.py
mathics/builtin/lists.py
mathics/builtin/recurrence.py
mathics/core/convert.py
mathics/core/expression.py
test/test_convert.py

I wrote a small fuzzing script and found a bunch of minor bugs. Mostly caused by not checking for `None` when calling `to_sympy()`.

Fuzz fixes

---

mathics/builtin/arithmetic.py
mathics/builtin/linalg.py
mathics/core/parser/parser.py
test/test_parser/test_parser.py

Added `Pi`, `Degree`, `Infinity`, `I` (two forms), and  `E` to the parser.

fix #431 and #274

---

mathics/web/media/js/mathics.js

This PR just disables spellchecking by setting the [HTML5 spellcheck attribute](https://www.w3.org/TR/html5/editing.html#attr-spellcheck) - doesn't seem like this buys us much, it doesn't help me spell `LaguerreL`

Disable spellchecking on query fields

---

mathics/builtin/numbertheory.py

Only for integers at the moment. Used in #455 tests.

implement Quotient

---

mathics/builtin/patterns.py

Just a very small fix for inconsistent formatting of `Pattern` with `Optional`:
```
In[1]:= a:b:c
Out[1]= (a : b) : c
In[2]:= a:(b:c)
Out[2]= a : b : c
```

Swap precedence values in FormatValues for Optional and Pattern

---

mathics/builtin/arithmetic.py
mathics/builtin/base.py
mathics/builtin/exptrig.py
mathics/builtin/specialfunctions.py

Add some more integral functions

---

mathics/core/definitions.py

Makes Mathics startup faster, by making the time in `contribute` in the `Definitions` constructor go to roughly 50% (from 2.5 to 1.1 s).

Faster insert_rule

---

mathics/builtin/base.py
mathics/builtin/inout.py
mathics/doc/doc.py

This is a precursor to a larger package (https://github.com/poke1024/Mathics/tree/nlp).
It allows `Builtin`s to define a `requires` attribute that lists Python modules that are needed for this Builtin. If not available, all `apply` methods in this `Builtin` will be automatically deactivated, an error will be output if the methods are called. Also, no test cases from these `Builtin`s are run, if the packages in `requires` are not installed in the test environment.
Here's an example how it works. First, define a some Builtin `DrSeuss`: 
```
class DrSeuss(Builtin):
requires = (
'drseuss',
)
def apply(self, x, evaluation):
'DrSeuss[x_]'
return x
```
Calling it will produce this:
`In[1]:= DrSeuss[1]
: DrSeuss[] is not available. Your Python installation misses the "drseuss" module
`

support for 'requires' attribute

---

mathics/builtin/base.py
mathics/builtin/inout.py
mathics/core/expression.py

A cleaner version of the `Atom` implementation used in `Image[]`, that makes it easy to add new `Atom`s, such as `Image[]`, `Graph[]`,  etc. without having to change central code in `MakeBoxes`.
Two changes:
(1) new `AtomBuiltin` (from #378); needed as a mechanism to register a builtin-like symbol that is actually an `Atom` (declaring an `Atom` directly does not register a name that could be used for constructing it in an `Expression`, so there always has to be an accompanying `Builtin`).
(2) moved out logic from `class MakeBoxes(Builtin)` into a new `Atom.atom_to_boxes` method, so that new `Atom`s need not add their logic (and import their symbols) to `MakeBoxes` but must instead provide an implementation of `atom_to_boxes`.
In the current implementation, `MakeBoxes` returns `None` on …

AtomBuiltin and decentral Atom box handling

---

mathics/builtin/graphics.py

This is in preparation of adding `Arrowheads` and `FontSize` soon.
The current code makes adding new `Style` directives cumbersome, as several places of definition and reference in the code need to be changed.
This PR reorganizes and unifies the places where style heads are declared into one central place, such that adding a new style means adding a new entry to `styles` at the end of the file and nowhere else.
I didn't reorganize `element_heads` (apart from making it a `set`) as some funky mixing of `Graphics` and `Graphics3D` objects is going on there, that I didn't understand.
I'm not sure what the `# noqa` comment in `_GraphicsElements.__init__` means, so I just left it. Is it 'no QA'?

Cleanup of Style definitions

---

mathics/builtin/arithmetic.py
mathics/core/expression.py

Avoids downgrading exact expressions to inexact ones when they don't
evaluate to a numeric result.
Before:
```
In[1]:= 1. + Sqrt[x]
Out[1]= 1. + x ^ 0.5
```
After:
```
In[1]:= 1. + Sqrt[x]
Out[1]= 1. + Sqrt[x]
```

Only numerify if the result is numeric

---

mathics/builtin/lists.py
mathics/builtin/patterns.py
mathics/builtin/strings.py
mathics/builtin/structure.py

Adds operator versions to several builtins. Uses the same approach already used in `StringPosition`.

Several Operator Versions

---

mathics/builtin/arithmetic.py
mathics/builtin/calculus.py
mathics/core/convert.py

These are some small improvements to `Piecewise[]`,  which improve things in my opinion, as `Piecewise[]` can now be used and is evaluated as soon as it gets into the regular Sympy pipeline.
`D` and `Derivative` still do not work as they don't use the Sympy pipeline and someone understanding `D`'s logic might want to look at this (I tried and failed).
adding `*` in the comparison (e.g. `LessEqual`) cases in `convert.py` is actually a bug fix; without it, `from_sympy` produces stuff like `LessEqual(List(a), List(b))`.

some small improvements to Piecewise[]

---

mathics/builtin/numeric.py
mathics/core/numbers.py

implement Rationalize

---

mathics/builtin/files.py
mathics/builtin/graphics.py
mathics/builtin/inout.py
mathics/core/evaluation.py
mathics/main.py
mathics/settings.py
mathics/web/media/js/mathics.js
mathics/web/views.py

I strongly suggest we merge the changes necessary to run Mathics as an imathics kernel into `master`. The current imathics branch is outdated and it's a pain to keep it updated. This is a proposal to add all necessary changes to master.
I've tested this with the experimental version in https://github.com/mathics/IMathics/pull/11 under Jupyter 5.

Changes for imathics kernel

---

mathics/builtin/arithmetic.py
mathics/builtin/base.py
mathics/builtin/graphics.py
mathics/builtin/inout.py
mathics/core/expression.py

Adds little color boxes to colors (i.e. classes derived from `_Color`) like `RGBColor[0, 1, 1]` in `StandardForm`.
This should have been a fairly simple format change, but I ran into obstacles with my new unit test, that should be testing that `RGBColor[0, 1, 0] // StandardForm` is now `-Graphics-`.
The test case didn't work, it just ignored my `//StandardForm` direction. And this was due to some special case handling in `mathics/core/expression.py` involving `OutputForm` and `StandardForm` (that I don't understand). Disabling it (as below) fixes my new test case, but breaks two old test cases, namely: `ToBoxes[a + a]` and `StandardForm[a + b * c]`. Both of these test `StandardForm` expressions (`ToBoxes` defaults to `StandardForm` if no second parameter is given), and they failed, …

Graphics boxes for colors

---

mathics/builtin/graphics.py

You can use `Style[]` and write something like:
`Graphics[{Style[Circle[], Thick], Circle[{1,1}]}]`
Did not work before, as `Style[]` was not supported.

support for Style[]

---

mathics/autoload/formats/Image/Export.m
mathics/autoload/formats/Image/Import.m
mathics/builtin/importexport.py

Somehow the context for `RegisterExport` was missing and so this didn't register properly and didn't work (it worked once). Also changed export file extension detection to case insensitive mode so we can now export to 'abc.PNG' as well.

fixes Image[] import and export

---

mathics/builtin/graphics.py

This adds `PointSize[]` and boosts the standard point size to something more like MMA.
Attached are two `ListPlot[{1, 10, 5, 3}]` pictures (before and after) to see the difference.
In order for the `PointSize[]` parameter to really scale with the actual width, I had to introduce `view_width`, since neither `extent_width` nor `pixel_width` measure the final, clipped area. This is important if something like `Graphics[{PointSize[0.3], Point[{0, 0}]}]` should work (which it does now). This is the same approach used in https://github.com/mathics/Mathics/pull/470, which works well there.

PointSize[]

---

mathics/builtin/graphics.py

Purely cosmetic this one. Here's a before after image pair:
If an axis consists of purely integer values, no decimal points are printed now. For floating point axes, a format of 'x.0' is used (instead of 'x.' as currently).

Change axis number to integers, if possible

---

mathics/builtin/__init__.py
mathics/builtin/manipulate.py

Ports Manipulate[] into the new combined IMathics/Mathics branch. Depends on https://github.com/mathics/Mathics/pull/480 and https://github.com/mathics/IMathics/pull/11.

Manipulate[]

---

mathics/builtin/arithmetic.py
mathics/builtin/comparison.py
mathics/builtin/graphics.py

These work with svg and asy (I've tested both with the accompanying test cases). One test case specifically demonstrates that the points generated by `BezierFunction` match the curve which defined through the svg/asy commands.
There are two changes to `Piecewise` in here needed for `BernsteinBasis` (and because I was too confused and committed this to this PR instead of a new one). `Piecewise` now holds all expressions, as some might not be evaluable, and only evaluates conditions.

FilledCurve[], BezierCurve[], BezierFunction[]

---

mathics/builtin/lists.py
mathics/builtin/patterns.py

BEFORE:
```
In[3]:= Timing[Position[Range[10000], 100]]
Out[3]= {2.08852, {{100}}}
In[2]:= Timing[Cases[Range[10000], Real]]
Out[2]= {4.01146, {}}
In[4]:= Timing[Length[DeleteCases[Range[10000], 100]]]
Out[4]= {5.31249, 9999}
```
AFTER:
```
In[3]:= Timing[Position[Range[10000], 100]]
Out[3]= {0.448546, {{100}}}
In[2]:= Timing[Cases[Range[10000], Real]]
Out[2]= {0.43542, {}}
In[4]:= Timing[Length[DeleteCases[Range[10000], 100]]]
Out[4]= {0.665926, 9999}
```
If you're dealing with 100 000 elements, this really makes a difference.

Speedups for Position[], Cases[], DeleteCases[]

---

mathics/builtin/strings.py

Avoids the use of `from_python` and thus gains 10% speed.

Faster StringSplit[]

---

mathics/builtin/graphics.py

Adds 2D implementations of `Arrow[]` and `Arrowheads[]`, which is a stepping stone towards `Graph[]`. The best illustration is to try out the accompanying test cases.
__EDIT__ ~~For custom arrows using `Graphics` some primitives, such as `Rectangle`, use a somewhat different coordinate space in MMA, where they end up not in the center but at the side of the line; this is a very special border case though in my opinion (for example `Circle` is fine) and I didn't want to investigate further.~~ fixed now
Does not include 3D support.

Arrow[], Arrowheads[]

---

mathics/builtin/graphics.py

Currently, if `PlotSize` is used without axes, it fails, e.g. `Graphics[{Rectangle[]},PlotRange->{{0,1},{0,1}}]` fails. This PR fixes this.

Fixes PlotSize

---

mathics/core/definitions.py

This continues https://github.com/mathics/Mathics/pull/501 with a more general approach.
Depending on the situation, the performance gain with this seems to be between 5% and 15%:
[before.txt](https://github.com/mathics/Mathics/files/437771/before.txt)
[after.txt](https://github.com/mathics/Mathics/files/437772/after.txt)

Cache for Definitions

---

mathics/builtin/arithmetic.py
mathics/builtin/control.py
mathics/builtin/lists.py
mathics/builtin/scoping.py
mathics/core/definitions.py
mathics/core/expression.py
mathics/core/rules.py

Fixes #531
Keep track of when each definition changes along with when each expression was last evaluated to prevent unnecessarily re-evaluating expressions.
I'm also wondering if the timestamps could be used to optimise definition caching as in #507.

Expression caching

---

mathics/builtin/system.py
mathics/main.py
mathics/script.py
setup.py

A new interface for writing scripts. Allows, e.g. 
```mathematica
#!/usr/bin/env mathicsscript
args = Rest[$ScriptCommandLine];
Print[Plus @@ args, " = ", (ToExpression /@ args) // Total]
```
```bash
> ./script.m 1 2 3
1 + 2 + 3 = 6
```

mathicsscript

---

mathics/builtin/exptrig.py
mathics/builtin/numeric.py

Seemed so simple, but is now quite elaborate since a special case for numerical evaluation seems important to me, as speed is an issue here.
One thing that vexes me is that numerical evaluation does not automatically get triggered when using this in `Graphics`, which means that a very slow symbolic evaluation is triggered inside `Graphics` if one does not specify numerical quantities. More specifically:
```
Timing[Graphics[Line[AnglePath[Table[90 Degree, {20}]]]]]
{3.6392160000000002, -Graphics-}
Timing[Graphics[Line[AnglePath[Table[1.57, {20}]]]]]
{0.013397999999999577, -Graphics-}
```
As you can see, the numerical evaluation (due to the special case in `AnglePath`) is about two magnitudes faster. I really wonder how we could get `Graphics` to do a recursive `N` on all its sub …

AngleVector[] and AnglePath[]

---

README.rst
mathics/algorithm/clusters.py
mathics/builtin/colors.py
mathics/builtin/image.py
mathics/builtin/options.py
mathics/builtin/plot.py

- Removed dependency on skimage everywhere where it's not strictly necessary; everything except for morphology and edge detection now only relies on PIL and numpy
- Removed matplotlib dependency
- Extended Colorize[] to use arbitrary ColorData[] and color functions (also works on images now)
- Added support for reading JPEG EXIF data via Import["image.jpg", "RawExif"]
- Extended ImageTake[] for general cropping
- Added ColorCombine[]
- Added DominantColors[]
- Added ImageConvolve[]
- Reimplemented BoxMatrix, DiskMatrix, DiamondMatrix to match MMA
- Added docs
I've added the scipy license to README.rst, since ImageConvolve[] is basically a port of their code, and we might want to adapt some other of their stuff in the future; I'm not sure if this is the right way, though.

Overhaul of image.py

---

mathics/core/expression.py
mathics/core/rules.py

Before: 
```
In[1]:= Timing[Map[StringJoin, Table[{"a", "b"}, {5000}]]]
Out[1]= {1.52122, <<1>>}
```
After:
```
In[1]:= Timing[Map[StringJoin, Table[{"a", "b"}, {5000}]]]
Out[1]= {1.26722, <<1>>}
```

Three small optimizations

---

mathics/builtin/lists.py
mathics/builtin/tensors.py

Only the `Scan` method is implemented here, but it's still quite useful, I think.

a basic version of Nearest[]

---

mathics/builtin/datentime.py

Adds more careful handling of different date formats for the completely automatic `DateList[s_String]` case.
This now gives a warning if the date cannot be unambiguously determined (also a test case now).

Better automatic date parsing for DateList[]

---

mathics/builtin/pympler/__init__.py
mathics/builtin/pympler/asizeof.py
mathics/builtin/structure.py
mathics/core/expression.py
setup.py

Implements ByteCount using the BSD-licensed asizeof module, which scans through the object tree and gives the total byte count of it. The results may differ between Python implementations and versions.

ByteCount using asizeof

---

mathics/builtin/__init__.py
mathics/builtin/compilation.py
mathics/builtin/compile.py
mathics/builtin/compile/__init__.py
mathics/builtin/compile/base.py
mathics/builtin/compile/compile.py
mathics/builtin/compile/ir.py
mathics/builtin/compile/types.py
mathics/builtin/compile/utils.py
mathics/core/evaluation.py
setup.py
test/test_compile.py

Allows compiling simple expressions with `llvmlite`.
At the moment nothing else is aware of `CompiledFunction` so the performance benefits are marginal (most of the time is spent looking for patterns) but this has the potential to speedup plotting significantly.
```mathematica
In[1]:= cf = Compile[{{x, _Real}}, Sin[x + 2]]
Out[1]= CompiledFunction[{x}, Sin[2 + x], -CompiledCode-]
In[2]:= data = RandomReal[1, 100];
In[3]:= Map[cf, data]; // Timing
Out[3]= {0.084535, Null}
In[4]:= Map[Sin[#1 + 2]&, data]; // Timing
Out[4]= {0.120563, Null}
```
Requires a minor bugfix to llvmlite: https://github.com/numba/llvmlite/pull/205.

LLVM compilation

---

mathics/builtin/assignment.py
mathics/builtin/functional.py
mathics/builtin/patterns.py
mathics/builtin/scoping.py
mathics/core/convert.py
mathics/core/expression.py
mathics/core/rules.py

Without this PR, this code crashes Mathics:
```
test[x_] := Module[{n = 1 + x}, Module[{b = 2 * n}, b * 2]];
test[1]
```
The reason is that `replace_vars` loses its evaluation. This PR fixes this such that the expression above evaluates properly.

Fixes a crash with Module[]

---

mathics/main.py

This sets `max_stored_size` to return `None`, so the check for pickle size that runs at the end of each evaluation in `Evaluation.get_stored_result()` will not be invoked, which saves time.

Faster TerminalOutput

---

mathics/builtin/evaluation.py
mathics/builtin/inout.py
mathics/core/evaluation.py
mathics/core/expression.py

This is a cleaned up, faster and better version of `$OutputSizeLimit`.
It now lives in its own class based on `_MakeBoxesStrategy` and makes the state more clean by using a dedicated class `_LimitedMakeBoxesState `. The whole code is now in `expression.py` to avoid the ugly in procedure imports needed for `Expression` until now.
There are two functional differences from the current code:
(1) The very first and the very last elements in a tree are now always output; e.g. `Nest[Partition[#, 2]&, Range[2 ^7], 7]` now yields `{{{{{{{{1, <<1>>}, <<1>>}, <<1>>}, <<1>>}, <<1>>}, <<1>>}, {<<1>>, {<<1>>, {<<1>>, {<<1>>, {<<1>>, {<<1>>, 128}}}}}}}}` (it yields a lame `{<<1>>}` with the current implementation).
(2) Every output that has been calculated using `MakeBoxes` is now always output and …

Update of $OutputSizeLimit

---

mathics/web/media/js/mathics.js
mathics/web/media/js/prototype/prototype.js

Undo/redo functionality implementation for the web interface (refer #68).
The input cells are implemented using `textarea` elements which have native browser undo/redo; however the specific way this works differs quite dramatically among browsers (e.g. Chrome vs. Firefox), and switching between cells can cause the undo history to be forgotten.
A custom implementation is much better.
**Tested on Firefox and Chrome; help testing on Safari appreciated.**
Notes:
-  No ability to undo deletion of cells.
- Undo limit can be set in `mathics.js`.

Implement undo/redo functionality

---

mathics/core/expression.py
mathics/core/rules.py

This PR introduces a special case for flattening sequences as it's an operation/border case deeply embedded into the rules and evaluation engine and executed nearly each time a rule is resolved.
The main advantage of the new approach is that symbols are now tracked during `Expression` construction, such that all paths leading to a symbol can be efficiently identified in any part of an `Expression` tree without having to revert to full tree traversals. In that way, all sub trees of an `Expression` not containing sequences don't have to be checked.
The original optimization targeted with this PR was faster handling of huge lists. E.g., using `list = Nest[Partition[#, 2]&, Range[2 ^ 14], 14]`:
Without this PR:
```
In[2]:= Timing[Length[list]]
Out[2]= {0.330744, 1}
```
With this PR:
``` …
```

Faster flatten for Sequence symbols

---

mathics/builtin/plot.py

Uses compiled functions for plotting. Works for everything except `ParametricPlot`.
```
DensityPlot
'DensityPlot[x + y^2, {x, -3, 3}, {y, -2, 2}]'
5 loops, avg:  441 ms, best:  273 ms, median:  391 ms per loop
Plot
'Plot[0, {x, -3, 3}]'
100 loops, avg: 26.8 ms, best:   11 ms, median: 19.4 ms per loop
'Plot[x^2 + x + 1, {x, -3, 3}]'
5 loops, avg:  280 ms, best:  187 ms, median:  257 ms per loop
'Plot[Sin[Cos[x^2]], {x, -3, 3}]'
5 loops, avg:  563 ms, best:  399 ms, median:  439 ms per loop
'Plot[Sin[100 x], {x, -3, 3}]'
5 loops, avg:  354 ms, best:  289 ms, median:  332 ms per loop
Plot3D
'Plot3D[0, {x, -1, 1}, {y, -1, 1}]'
100 loops, avg:   32 ms, best: 17.3 ms, median: 25.8 ms per loop
'Plot3D[x + y^2, {x, -3, 3}, {y, -2, 2}]'
10 loops, avg:  131 ms, best: 94.7 ms, median:  139 ms per …
```

basic compiling for _Plot and _Plot3D

---

mathics/builtin/datentime.py

This function is in the `Calendar` package in MMA, but then calling it in `Calendar` in MMA 10 gives you a warning and it's not clear what you should call instead (see http://mathematica.stackexchange.com/questions/75281/eastersunday-replacement-in-mathematica-10). So I assume we might as well add it to `System`.

Adds EasterSunday[]

---

mathics/builtin/lists.py

This PR reorganizes `walk_parts` and changes it to a pure functional (and read only) implementation. I hope it's also a bit cleaner as the variable scoping is more defined.
The targeted optimization is achieving runtime with `Parts[]` with big lists. Using `list = Nest[Partition[#, 10]&, Range[10 ^ 5], 5]`:
Without this PR:
```
In[2]:= Timing[Part[list, 1, 1, 1, 1, 1]]
Out[2]= {4.10712, {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}}
```
With this PR:
```
In[8]:= Timing[Part[list, 1, 1, 1, 1, 1]]
Out[8]= {0.985205, {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}}
```
~~~As far as I see, the `assign_list` parameter in `walk_parts` is never used in a call, so I didn't test the code there with the new changes; maybe this is some preparatory code for a feature to come but not there yet?~~~ **EDIT** assign_list is used and …

a faster walk_parts

---

mathics/builtin/patterns.py
mathics/builtin/strings.py

Adds `StringCases[]`, but also adds `Shortest[]` and `Longest[]` support for regular expressions, as well as patterns (e.g. `"a" ~~ x_ ~~ "c" -> x`). Also fixes border cases that were not previously supported, namely replacing with non-strings, e.g. `StringReplace["abc", "b" -> 4]`.

StringCases[] and more

---

mathics/builtin/scoping.py

Yesterday's fix for nested Modules (https://github.com/mathics/Mathics/pull/584) was not really correct. I added `evaluation` to the `replace_vars` pipeline, which is not a bad thing in itself, I guess. The problem is, though, that `Module` should not actually evaluate at that point, but only later when it gets to `new_expr.evaluate(evaluation)`. If it evaluates earlier, nested modules get evaluated, which is not what we want. I added this rather funky test case to demonstrate what happens if evaluation happens too early (it calls `Abort[]`).

Fixes nested Modules (again)

---

mathics/builtin/strings.py
mathics/core/rules.py
mathics/core/util.py

One recurring mini-grievance when writing `Builtin`s is to construct the input `Expression` when giving out error messages, which usually results in repeated fragments of code that looks something like this:
```
def apply(self, s, n, m, evaluation):
'StringRepeat[s_String, n_Integer, m_Integer]'
...
evaluation.message('StringRepeat', 'intp', 2, Expression('StringRepeat', s, n, m))
```
This PR now allows `apply` functions to specify a new parameter `expression`. If it's in the function's argument list, it will contain the expression that is being evaluated at this point. With this, the code above changes to:
```
def apply(self, s, n, m, expression, evaluation):
'StringRepeat[s_String, n_Integer, m_Integer]'
...evaluation.message('StringRepeat', 'intp', 3, expression)
```
The `StringRepeat` …

Add parameter for evaluated expression

---

mathics/builtin/image.py

more image docs and examples

---

mathics/builtin/assignment.py
mathics/builtin/evaluation.py
mathics/builtin/inout.py
mathics/builtin/lists.py
mathics/core/evaluation.py
mathics/core/expression.py
mathics/test.py

In the interest of getting 1.0 out I've decided to revert the `$OutputSizeLimit` changes introduced in #385 and #581. I'd like to add them back in eventually as it can really speed up large expressions (especially all the nice optimisations done by @poke1024).

revert $OutputSizeLimit

---

mathics/builtin/files.py
mathics/builtin/importexport.py
mathics/builtin/inout.py
mathics/data/ExampleData/Middlemarch.txt
mathics/data/ExampleData/copyright.csv

Using `Import` on a text file with wrong unicode sequences currently crashes Mathics. This works around the problem, allowing the file to be imported with the problematic characters being replaced by whitespace.

Fix unicode decode problems

---

mathics/builtin/combinatorial.py
mathics/builtin/exptrig.py
mathics/builtin/patterns.py
mathics/builtin/strings.py
mathics/core/expression.py

Turns out that, at least in CPython, declaring `class`es inside functions is quite slow.
Running `x = Range[50000]; First[Timing[Position[x, 10000]]]` without this PR gives `1.16326`, with this PR, it gives `0.461211`. This is only due to one inner `class` definition.
Running the profiler, one actually sees Python's class build function popping up. So this PR moves inner classes out of functions at several places.

Speedups by avoiding inner classes

---

mathics/builtin/structure.py

When I coded this, I didn't understand that `Identity` is never an instance here.

Fixes Identity in BinarySearch

---

mathics/core/expression.py

Some nice speed-ups for cases when the `Expression` is actually the same.
[without-fast-same.txt](https://github.com/mathics/Mathics/files/536025/without-fast-same.txt)
[with-fast-same.txt](https://github.com/mathics/Mathics/files/536026/with-fast-same.txt)

Faster Evaluation.same()

---

mathics/autoload/formats/CSV/Export.m
mathics/autoload/formats/CSV/Import.m
mathics/autoload/formats/Text/Export.m
mathics/autoload/formats/Text/Import.m
mathics/builtin/base.py
mathics/builtin/files.py
mathics/builtin/importexport.py
mathics/builtin/inout.py
mathics/builtin/logic.py
mathics/builtin/options.py
mathics/builtin/patterns.py
mathics/builtin/strings.py
mathics/builtin/xmlformat.py
mathics/core/expression.py

This adds the `CharacterEncoding` option to text and csv `Import` and `Export`, as well as to `FromCharacterCode` and `ToCharacterCode`.
Along the way, I encountered quite a number of things I needed to add/change, specifically:
- importers and exporters may now specify `Options` and they are passed down to the respective calls
- options are now parsed very leniently; it doesn't matter whether you write `X -> 1` or `"X" -> 1`; it also doesn't matter if X has been declared a `System` symbol or not (i.e. it doesn't matter if `X` resolves to ```System`X``` or ```Global`X```.
- `FilterRules`
- `AllTrue`, `AnyTrue`, `NoneTrue`

CharacterEncoding and more

---

.travis.yml
mathics/builtin/image.py
mathics/builtin/natlang.py
travis.py

Travis CI currently seems to break due to a change in spacy's `en` corpus. This PR seems to fix it by installing a specific version of the corpus using `sputnik`.
Another (new) problem is that `DominantColors` fails. I think this might be due to some changed `PIL` version. Therefore, this PR adds print outs of versions of all installed modules to enable looking into this further now (as well as in the future).

Fixes Travis

---

.travis.yml

Wow, this gets annoying.
Spacy 1.0.4 introduces a bug that breaks Python 3.5 builds (only those).
So this pins Spacy to 1.0.3, which solves the problem.

Fix Travis again

---

mathics/builtin/manipulate.py

This got broken with the `imathics` branch merge into master. There is no `format_all_outputs` anymore. Works now.

Fixes Manipulate[x,{x,{a,b}}]

---

mathics/core/parser/convert.py

Introduces `GenericConverter` which returns tuples that describe the data that should be created (instead of directly creating the respective Python classes). This makes it cleaner to call this functionality from C or C++ via the Python C interface to then construct native C/C++ classes for integers, symbols, etc. in C/C++.

C/C++ interface to parser's converter

---

mathics/builtin/importexport.py

Some pages (e.g. `http://www.nytimes.com/interactive/2016/us/elections/polls.html?_r=0`) need cookies, or they won't import

Fixes loading of certain HTTP pages

---

mathics/builtin/natlang.py

It seems that the interface of pycountry have changed, and the current mathics master branch shows a fail in travis when this command is tested. This pull request fix the issue.

fixing LanguageIdentify issue.

---

mathics/builtin/xmlformat.py

Fixes failing Travis tests.
Ping @poke1024 (author of xml module).
New version of lxml changes the error messages by adding a suffix `(line 1)` for py2 and `(<string>, line 1)` for py3. Workaround is to strip these suffixes off.

fix XML tests

---

mathics/core/pattern.py

This actually has no effect in its current form (i.e. in `master`).
When applied to the `qtime` branch (https://github.com/mathics/Mathics/pull/619) though, it speeds up things quite considerably and effectively gives Mathics a whole new, snappy feeling when working with large lists.
Before (i.e. untampered https://github.com/mathics/Mathics/pull/619):
```
In[1]:= x = Range[100000]; Timing[Combinatorica`BinarySearch[x, 100]]
Out[1]= {0.142646, 100}
```
After:
```
In[1]:= x = Range[100000]; Timing[Combinatorica`BinarySearch[x, 100]]
Out[1]= {0.000985, 100}
```
In the non-ordered case, `leaf_candidates` is actually only used in the call to `subranges`, only that it's currently not used there; a future implementation should be fine with a list as well.

Speed up pattern matching for large lists

---

mathics/builtin/algebra.py

I am planning to add Coefficient[] and CoefficientList[]
This work in in-progress, this pull request is created to trigger automated tests
**Notes for Coefficient:**
- Modulus is not supported
- 2 test cases are failed because of Sympy bug
<pre>Coefficient[(x + 2)/(y - 3) + (x + 3)/(y - 2), z, 0]
The correct result should be (2 + x) / (-3 + y) + (3 + x) / (-2 + y)
but Sympy 1.0 returns 0</pre>
<pre>Coefficient[a x^2 + b y^3 + c x + d y + 5, x, 0]
Correct result: 5 + b y ^ 3 + d y
Sympy 1.0 returns: 5</pre>
This bug has been fixed in current [sympy-master](https://github.com/sympy/sympy)

Add Coefficient*[]

---

mathics/builtin/image.py

A backwards incompatible change in the `wordcloud` library broke the all_modules build. This cleans up the WordCloud implementation and fixes the build.
First reported by @hailongnk

fix WordCloud wordcloud.generate_from_frequencies change

---

.travis.yml
mathics/builtin/arithmetic.py
mathics/builtin/calculus.py
mathics/builtin/combinatorial.py
mathics/builtin/image.py
mathics/builtin/linalg.py
mathics/core/convert.py
setup.py
test/test_convert.py

Currently two tests are commented out because the way sympy returns derivatives by default seems to have changed.
It's just a cosmetic change, as it should work fine either way.

implement support for sympy 1.3

---

mathics/autoload/formats/CSV/Export.m
mathics/autoload/formats/CSV/Import.m
mathics/autoload/formats/Image/Export.m
mathics/autoload/formats/SVG/Export.m
mathics/builtin/files.py
mathics/builtin/importexport.py
mathics/builtin/pymimesniffer/magic.py

I included also some small fixes in Import and Export to avoid duplicate code. The implementation accept both formats Importer/Exporter with FunctionChannels {"FileNames"} and {"Streams"}. However, in the first case, the creation of a temporal file is required.
There is also a change in  the CSV importer/exporter to work with {"Streams"} as FunctionChannels, in a way to write simpler test cases.

Adding ImportString and ExportString functionalities

---

mathics/builtin/calculus.py
mathics/builtin/lists.py

This pull request includes the implementation of the following functions:
- Integers[]
- PrependTo[]
- ContainsOnly[]
Note: The IPython API version 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2. So I have changed the .travis.yml to install IPython 5.0 for covering all the test cases.

Adding 3 new functions: Integers, PrependTo and ContainsOnly

---

mathics/builtin/lists.py

Added Delete command

---

mathics/builtin/algebra.py
mathics/builtin/image.py
mathics/core/convert.py
mathics/core/expression.py

Hello,
I did [some work](https://github.com/skirpichev/Mathics/tree/diofant-experiment) to make Mathcis codebase working on a different CAS kernel, the [Diofant](https://github.com/diofant/diofant).  To my surprise, it works quite well (test pass locally) and required changes are small.
Not sure if Mathics developers will be positive on making Python CAS backend swichable, but here some simple fixes from the mentioned branch. I hope, this could be useful on its own.

Don't use p/q of Rational + import cleanup

---

mathics/builtin/arithmetic.py
mathics/builtin/numbertheory.py

- This PR includes the implementation of 3 functions:
+ MantissaExponent
+ FractionalPart
+ CubeRoot

Adding some functions in numbertheory and arithmetic

---

mathics/builtin/linalg.py

This is a follow up to https://github.com/mathics/Mathics/issues/795. Although Mathics had no problem computing the eigenvalues and eigenvectors of complex matrices, it tried sorting them before returning the results, which caused errors. This PR makes it so that the results are only sorted whenever it's possible to do so.

Fixed the behaviour of Eigenvalues and Eigenvectors

---

mathics/builtin/graphics.py

On line 12, `sin, cos, pi` are already imported from `math`, but are then imported again on line 19.

graphics.py: Remove duplicate imports

---

mathics/builtin/assignment.py
mathics/builtin/evaluation.py
mathics/main.py

I'm not quite sure what the implications of changing the functionality of `Quit` are but this is more consistent with Mathematica.

Quit and Exit

---

mathics/builtin/evaluation.py

Fixed #813 and made it so that `Quit` quits Mathics (instead of `Quit[]`).

Fixing Quit[]

---

mathics/builtin/arithmetic.py

This makes `Re[Sqrt[z]]` and `Im[Sqrt[z]]` work properly.

Implemented proper sympolic expantion for the Re and Im builtins

---

mathics/builtin/evaluation.py

There was a bug that caused the exit code in `Quit[n]` to be ignored. It's now fixed, but the `Quit` shortcut for `Quit[]` doesn't work anymore.

Fixed the behaviour of `Quit`

---

mathics/builtin/assignment.py
mathics/core/parser/operators.py
mathics/core/parser/parser.py
mathics/core/parser/tokeniser.py
mathics/doc/doc.py
test/test_parser/test_parser.py
test/test_parser/test_tokeniser.py

Finally, I could add the prefix operators ? and ?? with its standard mea ning in mma: ? F is equivalent to Definition[F] and ??F calls Information[F].
I also added the command Information, which for built in symbols, shows the **doc** string of the correspondent class, and for user symbols, looks to the message ::usage.
Something that is missing is to show inside Information the output of Definition, but for some reason it didn't work. Anyway, I think the basic functionality is implemented.

Information

---

mathics/builtin/graphics.py
mathics/builtin/graphs.py
setup.py

`graphics.py` `extent()`: For `EdgeConnectivity[Graph[{}]]`
`total_extent()` can return `[None, None, None, None]` for {x,y}m{in,max}. So check for this and dissallow `None *= 2 `
`graphs.py` ` _path_layout():` For `PathGraph[{1, 2, 3}]`  `neighbors` is a generator, so `next(neighbors)` is used instead of
`neighbors[0]`. 
Unused imports and trailing blanks have been removed. (My editor did the latter, my programming environment suggested removing the unused imports)

Fix two `python mathics/test.py -o` errors

---

mathics/builtin/pympler/asizeof.py

It looks like a copy of Pympler's asizeof.py is include.
However this produces (in more recent Pythons) the decprecation message:
```
asizeof.py:217: DeprecationWarning: unicode_internal codec has been deprecated
u = u.encode('unicode-internal')  # see .../Lib/test/test_sys.py
```
This has been reported in the Pympler project and folks finished
addreessing around Apr 6, 2019.
See https://github.com/pympler/pympler/issues/74

update asizeof.py to remove deprecation message

---

mathics/builtin/diffeqns.py
mathics/builtin/exptrig.py
mathics/builtin/files.py
mathics/builtin/inout.py

In older Python's backslash (`\`) followed by a symbol that is not an by
one of the acceptable escape characters was okay and would be the two
symbols. For example `"\["` would represent the string `"\["`.
In more recent Python, a deprecation warning is given for backslash that
isn't followed by an accepted escape character now gives a deprecation
warning. What is expected in these cases is the escape the escape, .e.g
`\\[`.

Remove deprecation warning associated with \

---

test/test_console.py

It becomes assertRegex instead.
For the most part, I think this is the last of the deprecation warnings.
Again. running `black` format is a separate commit in case that is not desired.

Remove assertRegexpMatches DeprecationWarning

---

README.rst

This PR steals the relevant commits from https://github.com/mathics/Mathics/pull/753. It's a fix for #751.

Added mentation about docker images in the documentation

---

mathics/builtin/files.py
mathics/builtin/inout.py
mathics/builtin/lists.py
mathics/core/expression.py

Fixed #538. This was fixed by @sn6uv in https://github.com/mathics/Mathics/pull/539. I just rebased his commit.

InputForm should escape backslash

---

mathics/builtin/plot.py
setup.py

#499 rebased. @poke1024 @sn6uv please double check. 
My take is that however incomplete and imperfect this is, it is better than the nothing that we have there and Bar Charts, Pie Charts and Density Plots are nice to have.

Add BarChart, PieChart, and DensityPlot

---

.travis.yml
mathics/doc/doc.py
mathics/doc/tex/Makefile
mathics/doc/tex/latexmkrc
mathics/doc/tex/mathics.tex

Well, 
I was able to fix the utf8 errors using xelatex instead of pdflatex, and the issue of the empty tests. There are still errors coming from the asy interface for graphics generation. I am not an expert on that package, so I will need some help from here. Otherwise, we could simply remove the tests that generate problematic graphics.

Fix documentation errors regarding UTF8

---

mathics/builtin/arithmetic.py
mathics/core/expression.py

Fixed a bug concerning the behaviour of the `Sum` and `Product` builtins.
```
In[1]:= Sum[f[i], {i, 1, 7}]
Out[1]= 7 f[i]
```
```
In[1]:= Sum[f[i], {i, 1, 7}]
Out[1]= f[1] + f[2] + f[3] + f[4] + f[5] + f[6] + f[7]
```

Sum product fix

---

Makefile
mathics/Makefile
mathics/doc/Makefile
mathics/doc/tex/Makefile
pymathics/Makefile

We need to run python mathics/test.py *twice*
Once with -o, and *then* once with -t. We can't combine these options.
Add top-level "clean" target.
Add .PHONY targets and do it properly
Turn a make comment into a remake-style comment.

Various Makefile bug fixes and improvements

---

mathics/builtin/numeric.py
pymathics/setup.py
pymathics/testpymathicsmodule/__init__.py

We don't do Python 2.x anymore, so we don't need six.

Remove dependency on six

---

mathics/core/evaluation.py
mathics/web/models.py
mathics/web/views.py

In-memory sessions

---

.travis.yml

I have finally found the problem: pypy3 needs to compile the llvmlite package, and needs the version 10 of the llvm package. But to do that, we need to set up first an environment variable to tell the system to use that version instead of the default (version 7).

Fixing  llvm

---

mathics/builtin/base.py
mathics/builtin/importexport.py
mathics/builtin/options.py
mathics/builtin/plot.py
mathics/core/rules.py

Currently, if options are given for commands that are not supported, they are simply ignored. This can be very confusing for novice users, especially if they mistype an option (e.g. `FieldSeperetors` instead of `FieldSeparators`).
This PR adds a new meta option called `$OptionSyntax` that may be either `Strict`, `Warn` or `Ignore`, and defines what should happen, if the user specifies an option that does not show up in  the `Builtin`'s `options` dictionary.
The default (also used if no `$OptionSyntax` is specified) is to give a warning but continue with evaluation. `Strict` gives a warning and stops the evaluation (this happens for `Plot`). `Ignore` is the old behavior. 
In addition to this, this PR adds custom checks for `Import` and `Export` that gives warnings for options that are not …

Give warnings when using options not supported by a Builtin

---

mathics/doc/doc.py

I implemented now a "default" name, based on the name of the python module, without the prefix "pymathics".

Default name for pymathics modules

---

mathics/autoload/formats/PACKAGE/Import.m

Here, as asked by @rocky I included a small fix to support loading packages with the syntax
Import@"package.m"

adding Import for M packages

---

mathics/builtin/inout.py
mathics/doc/documentation/1-Manual.mdoc

I recently found that I like sans serif MathML fonts much better as they match the general Jupyter theme I use:
Maybe this is also interesting for https://github.com/mathics/Mathics/pull/574, as this seems to use sans serif fonts for the code input? Here's what it looks like in the non-spiffified `mathicsserver`:
I wonder where this should be configured;`settings.py` doesn't seem a good place to me.

Option to use sans serif fonts for MathML

---

mathics/autoload/formats/Base64/Import.m

In Mathematica, There shouldn't be a trailing "," in a List.

Fix Mathematica syntax warning in Import.m

---

mathics/builtin/linalg.py

Here's the stack-trace for the bug in question:
```
Traceback (most recent call last):
File "/home/pablo/.local/bin/mathics", line 361, in <module>
main()
File "/home/pablo/.local/bin/mathics", line 344, in main
result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
File "/home/pablo/Documents/Mathics/mathics/core/evaluation.py", line 286, in evaluate
result = run_with_timeout_and_stack(evaluate, timeout)
File "/home/pablo/Documents/Mathics/mathics/core/evaluation.py", line 95, in run_with_timeout_and_stack
return request()
File "/home/pablo/Documents/Mathics/mathics/core/evaluation.py", line 264, in evaluate
result = query.evaluate(self)
File "/home/pablo/Documents/Mathics/mathics/core/expression.py", line 863, in evaluate
expr, reevaluate = expr.evaluate_next(evaluation)
File …
```

Fix bug in the Cross implementation

---

mathics/core/expression.py

Outputting parts of a list recomputes the format for everything each time an output happens.
Thus, outputting `x=Partition[Range[10000], 5]`, `x`, `Drop[x]` always calls `do_format` on each node of the whole tree.
For XML data of a few KB `do_format` alone takes 1 to 2 s on my machine.
This PR caches `do_format` for trees and sub trees that were already output once. This depends on https://github.com/mathics/Mathics/pull/575 as without it, a whole tree traversal is needed to check the cache, which invalidates the benefit.

Adds a cache for do_format

---

mathics/builtin/patterns.py
mathics/core/pattern.py

I came across this while using `GatherBy`; without this PR, `x = Range[5000]; First[Timing[GatherBy[x, OddQ]]]` evaluates to `29.0664`, with this PR this changes to `0.517357`.
The basic problem is described in the comment in `yield_choice`: sub patterns that are very expensive to check are tested, even though the Blank match should be obvious.
Seems to give a very slight but measurable improvement in runtime.
[master.txt](https://github.com/mathics/Mathics/files/534476/master.txt)
[fastblank.txt](https://github.com/mathics/Mathics/files/534477/fastblank.txt)

Faster leading blank patterns

---

mathics/builtin/combinatorial.py

Adding function Subsets to the mathics

---

mathics/core/pattern.py

per_expr() needs to return a in interator return, not the default implied
`return None` as can happen.
In Python 3, // is used for truncated integer division. In Python 2 it
was /. That now returns float in Python 3.
Note the brokenness of self.get_wrappings
To reproduce brokenness before build, in `mathics` run:
```
<<"https://raw.githubusercontent.com/rebcabin/Mathics/master/mathics/packages/GS3.m"
```

Fix runtime bugs seen from GS3.m in per_expr()

---

README.rst
app/Dockerfile
app/entrypoint.sh
app/requirements-tmathics.txt
app/requirements.txt
docker-compose.yml
mathics/settings.py

https://hub.docker.com/repository/docker/rockyb/mathics has a more recent docker contrainer for 1.1-dev.
The natlang module isn't built, but I don't think right now that's important. Never let perfection get in the way of progress.
Issue #927 has been created to track remaining steps.
@suhr @GarkGarcia @mmatera  If you have docker and get a chance, I'd appreciate it if you could try out the instructions to verify this works.

Revise docker setup instructions

---

mathics/doc/doc.py
mathics/test.py

Also, Skip sandbox tests *only* if environemnt variable SANDBOX is not
set
--count is expected to facilitate going over the docstrings for new builtins
@suhr - note that in the PR we only skip `S>` marked tests if the environment `SANDPOX` is not set.

Add test.py --count arg

---

Makefile
mathics/__init__.py
mathics/builtin/assignment.py
mathics/builtin/datentime.py
mathics/builtin/evaluation.py
mathics/builtin/files.py
mathics/builtin/functional.py
mathics/builtin/plot.py
mathics/builtin/scoping.py
mathics/builtin/structure.py
mathics/builtin/system.py
mathics/doc/doc.py
mathics/test.py
tmp/README.rst

Doc system updates & pass over docs
* S> and X> directives were broken. They are less broken now
* struction.py: Combinatorica -> CombinatoricaOld since this is really obsolete
* doc/doc.py: fix S> and X>
Go over examples in system.py
Finally! No required trailing blanks!
Add `#<--#` to the end of a test line to signify that the test ends in a single blank

Review docs system; no trailing blanks required

---

mathics/builtin/importexport.py
mathics/builtin/inout.py
mathics/doc/documentation/1-Manual.mdoc
mathics/web/media/js/inout.js

Having used both for a while, as others in the past have observed SansSerif looks nicer than without.
Now that we have online docs this is all the more apparent.
(Not sure why we center, things either way, but I guess that's different)
In discussing this with Gark, the feeling is that it would be nice if we had a user profile for preferences like that could set.
However we don't have that right now. Given this my take is SansSerif is a better default.

Set to use SansSerif by default

---

mathics/builtin/__init__.py
mathics/builtin/assignment.py
mathics/builtin/base.py
mathics/builtin/datentime.py
mathics/builtin/inout.py
mathics/builtin/iohooks.py

There are a number of built-ins that don't want to be Protected by default, and we currently have no way to indicate that.
Currently "MakeBoxes" is hacked in to change this and "assignment" has another hack to change this as well. And they do this using the `List#clear()` function which removes *all* attributes, not just Protect.
In this change, setting the `attribute = ("Unprotect", ...)`  indicates to Builtin we don't want to add the "Protect" attribute.
Note however this isn't a true attribute like "Protect" is - it only means something in the declaration of a Builtin, and doesn't exist at run time.
The need for this change becomes all the more important as we move things into PyMathics because a growing number of these for variable-like definition will be desired.
Another Note: in the …

Remove "Protect" Attribute hackiness on Builtin

---

mathics/session.py
test/test_evaluation.py

In this PR, I added a module "mathics.session" which defines a class MathicsSession. This simplifies the integration of Mathics with Python code, skipping the need of running the command line interpreter. @rebcabin  I guess this would give a better answer to your question in the mathics google group.

Mathicssession

---

mathics/builtin/assignment.py
mathics/builtin/attributes.py
mathics/builtin/system.py
mathics/core/definitions.py

Here are the improvements in  #995  that are currently functional.

Assignnamepattern

---

mathics/packages/DiscreteMath/CombinatoricaLite.m
test/helper.py
test/test_combinatorica.py
test/test_evaluation.py

From combinatorica 0.6 add:
* BinarySearch,
* KSubsets,
From combinatorica 2.0 add:
* Compostions,
* CyclicGroup,
* DihedralGroupIndex,
* OrbitInventory,
* KSetPartitions,
* TransposePartition
* SetPartitions
* LastLexicogrpahicTableau
Add test/helper.py to DRY testing.

Expand via combinatorica 0.6 routines

---

mathics/builtin/control.py
test/test_control.py

"Catch[] needs to make sure it controls the expression evaluation
rather than having its expression get evaluated before it has a
change to wrap it in a `try`.
Internally, a plain `raise` is a bit more tidy Python wise
since the Python traceback will the path from raise to handler without
intervening tests of inappropriate exception handlers. This is a
matter of taste though.
Add more unit test tests.

Small tweaks, more tests

---

mathics/builtin/pympler/asizeof.py

Don't try "support" numpy.matrix since this is deprecated
Another option is to silence the deprecation warning  if we need to support the deprecated numpy feature.
Thoughts?

numpy matrix is deprecated so remove it

---

mathics/builtin/system.py
test/helper.py

Currently set to the most recent Mathematica release so that
packages that test on $VersionNumber are not thwarted.

Add System`VersionNumber

---

CHANGES.rst
mathics/builtin/files.py
mathics/packages/DiscreteMath/Kernel/init.m

lso Symbol("Null") -> Symbol(Null) os.path -> osp

Fix `InputFileName`; start `FileNameTake`

---

mathics/builtin/graphics3d.py
mathics/doc/doc.py

Also rstrip() was used improperly.
I don't know why it took me so long to get this fixed properly.

Finally! Explicit noting of blank at of end of line

---

mathics/builtin/arithmetic.py
mathics/builtin/numeric.py
mathics/core/expression.py

Also added  is_approx_zero which is like is_zero but approximate.
This may need more thinking and work more seemlessly within
the guidelines of how WL works.

Add PossibleZeroQ

---

mathics/core/util.py

This a fix for the first issue described in #1107. The issue was my fault, it's an error in the `UNICODE_TO_WL` dict.

Fix bug that converts `=` to `\uf7d9` in `replace_unicode_with_wl`

---

test/test_evaluation.py

In hte test here, I have tried to reduced all the duplication that appears in the code. 
There is one test 
```
(
"""Options[f2]:={s->12}; f2[x_,opt:OptionsPattern[]]:=x^OptionValue[s];
f2[y]""",
"y ^ 12",
)
```
either before or after the change that isn't working. (The "after" is surprising since underneath they do the same thing.)
I tried this in a mathics session and it doesn't work either.  I get:
```
y ^ OptionValue[s]
```
Does this work for you?

DRY code, comment out not-working test

---

test/test_evaluation.py

Revert "DRY code, comment out not-working test"

---

mathics/builtin/arithmetic.py
mathics/builtin/calculus.py
mathics/builtin/linalg.py
mathics/core/expression.py

Add option to compute Eigenvectors with mpmath
We should add this option more pervasively.
When converting from mpmath complex, convert to real number
when imag is 0.
We should also consider converting to int's too when possible.

Mpmath eigenvalues

---

mathics/builtin/comparison.py

Handle Equal/Unequal for Strings better.

---

mathics/builtin/integer.py

I am guessing Python 2.7 allowed reversed() on a generator.
3.7+ doesn't. Bug was probably around but not noticed until
expanded testing of combinatorica.
Also blacken buffer.

Bug fix reversed() used on generator

---

.github/workflows/osx.yml
.github/workflows/ubuntu.yml
examples/symbolic_logic/gries_schneider/test_gs.py
mathics/benchmark.py
mathics/builtin/arithmetic.py
mathics/builtin/evaluation.py
mathics/builtin/files.py
mathics/core/evaluation.py
mathics/core/parser/__init__.py
mathics/core/parser/feed.py
mathics/core/parser/util.py
mathics/main.py
mathics/session.py
mathics/test.py
setup.py
test/helper.py
test/test_file.py
test/test_to_python.py

The PossibleZeroQ failure I think was a break from before and another branch may fix.
The RecursionLimit failure I'll investigate later.

Use mathics scanner release

---

mathics/builtin/arithmetic.py
mathics/core/evaluation.py
mathics/core/expression.py

* a fraction is zero if the numerator is zero and the denominator is not zero. 
* fix MachineReal.is_approx_zero

Fix PossibleZeroQ

---

mathics/builtin/files.py
mathics/builtin/numeric.py

Part of the improvements in PR #1104

improving support for Hash and FileHash functions

---

mathics/builtin/importexport.py

WIP: improving support for import/export internals

---

mathics/builtin/assignment.py
mathics/builtin/base.py
mathics/builtin/inout.py
mathics/core/definitions.py
mathics/doc/doc.py

Here, there are some improvements in the way ``Information`` symbol works, coming from PR #1144. Over this, there is also an improvement regarding the connection between Definition objects and Builtin objects, allowing to a better decoupling between the mathics core module and the loading of ``pymathics`` modules: docstrings are now acceded throw the ``builtin`` property of the definition object, instead of looking at the mathics.builtin.builtins dictionary.

Fixing Information

---

mathics/core/definitions.py

The aim of this PR is to add a hook in the pymathics_load function in a way that once a module is loaded, we can add some definitions (for example, adding Import/Export formats) that require access to the Definitions object who is loading the module.

adding onload hook to pymathics

---

mathics/autoload/formats/Base64/Export.m
mathics/builtin/lists.py
mathics/core/expression.py

This PR fix some issues of the current implementation of ByteArray, and covers new functionalities like conversions to Normal List objects.

ByteArray implementation enhancements

---

CHANGES.rst
mathics/builtin/compilation.py
mathics/builtin/functional.py
mathics/core/expression.py

In this PR, some ideas to improve the support of ``System`Compile`` are implemented, in a way more generic expressions can be converted to a python callable object, including complex valued functions. 
This mechanism is also used to implement a better behaviour for to_python over ``System`Function`` expressions: when called on these kind of expressions, to_python returns a python callable object which can be passed to things like optimizers and integrators.

Implementing Compile for non compilable llvmlite functions as python functions

---

README.rst

I was reading the README and I think there is a missing space on `readthe docs guide`.
Feel free to close if this is not the case.

Fix missing space on README

---

mathics/autoload/settings.m

Back to you @mmatera. Just added a usage string.

Add usage string

---

mathics/builtin/graphics.py

@mmatera I used [`git bisect`](https://thoughtbot.com/blog/git-bisect) and tracked the graphics misbehaving to 616dbbae9c9480878c0752488724a74b61640b99  and specificlly the one-line change here. 
What does this change make possible? If we can't figure out something that accomodates both concerns, maybe we can add a setting so both ways are possible.
BTW This PR is the kind of thing I was mentioning about large PR's that are hard to follow. 
The title of  #1173 is "adds FileNames, a symbol required in the FeynCalc package"  and I don't see how this change which is about graphics has anything to do with ByteArray or FileNames. Even the commit message "fix write"  isn't suggestive.

mglyph -> mtext broke some images

---

CHANGES.rst
mathics/builtin/assignment.py

This PR allows to handle the situation involving assignments with several conditions:
```
F[x_,y_]/; x>0 /; x<y:= x/y
F[x_,y_]/; x<0 := 0
F[x_,y_]:=y/x
```

Handle successive conditions in SetDelayed

---

mathics/builtin/graphics.py

@mmatera with a change to the text opacity, I think we get most of the axis ugliness addressed. Also there is one slight adjustment to how svg `<text ..../>`  is set up. 
Let me know what you think.

Svg axis and text opacity

---

CHANGES.rst
mathics/autoload/formats/SVG/Export.m
mathics/builtin/base.py
mathics/builtin/compilation.py
mathics/builtin/graphics.py
mathics/builtin/graphics3d.py
mathics/builtin/image.py
mathics/builtin/importexport.py
mathics/builtin/inout.py
mathics/core/expression.py
mathics/test.py
test/test_custom_boxconstruct.py

This PR fixes 
* the internal generation of SVG images from the internal generator (to_svg) including text inside (like labels)
* the Export of graphics (and symbols) to a valid SVG.
This is achieved by using `boxes_to_text` instead of `boxes_to_xml` in the `InsetBox.to_svg` method. 
This still does not fixes the issue with the Django's interface: if we use `<mtext><img ...><\mtext>`, images are not properly bounded in the front end. On the other hand, this trick does not helps if we use `<mglyph ...>`: boundaries are correct in this case, but labels does not appears. I keep this last form, that can be handled making small modifications to `mathics.js` in the Django frontend (the change in  the corresponding PR).

Fix to svg

---

CHANGES.rst
mathics/builtin/strings.py

`StringSplit`: adding support for handling lists as a first argument

---

mathics/builtin/strings.py

This is used in the package ``KnotTheory``, and will help in the decoupling of evaluation / formatting of expressions.

support for ``form`` parameter in ToString

---

mathics/builtin/files.py

By default, I set ``$BaseDirectory`` equal to ``$InstallationDirectory``, and ``$UserBaseDirectory`` as ``~/.mathics``. Maybe we need to ensure that such a directory exists when a ``Definitions`` is created. On the other hand, maybe we could choose a better place for this configuration directory.

adding  ``$BaseDirectory`` and ``$UserBaseDirectory`` . Required by Feyncalc

---

test/helper.py
test/test_files.py

That is, in a way that doesn't depend on OS characteristics or
specifics of how Compress compresses things.
Simplify test/helper.py and remove unused imports.
BTW: I think ToString should be the exception not the rule.
In other words the defaults to_string_expr and to_string_expected should
be opposite of what it currently is.

Handle Compress/Uncompress checks better..

---

mathics/builtin/arithmetic.py
mathics/builtin/base.py
mathics/builtin/calculus.py
mathics/builtin/comparison.py
mathics/builtin/compilation.py
mathics/builtin/compile/ir.py
mathics/builtin/image.py
mathics/builtin/inout.py
mathics/builtin/linalg.py
mathics/builtin/lists.py
mathics/builtin/manipulate.py
mathics/builtin/numeric.py
mathics/builtin/patterns.py
mathics/builtin/strings.py
mathics/builtin/tensors.py
mathics/core/definitions.py
mathics/core/expression.py
mathics/core/numbers.py
mathics/core/pattern.py
test/test_hash.py
test/test_parser/test_convert.py
test/test_parser/test_util.py

* same -> sameQ with docstring and return value.
* do_compare -> equal2 (two argument Equal)
* sameQ properly implemented in the base class.
This is the last of the small cleanups before a more major refactor.

same -> sameQ; do_compare -> equal2

---

mathics/builtin/calculus.py

According to the WL reference, ``Derivative`` has attributes ``NHoldAll``, and ``ReadProtected`` but not  ``Protected``. This address the issue #1263

Unprotect Derivative (fix issue #1263)

---

mathics/builtin/system.py

This tries to address in a very basic level #1258

memory functions

---

CHANGES.rst
mathics/builtin/patterns.py

This fix partially #1261: 
``Dispatch[x_]->x``
The next step would be to enlarge this method, in order to check that all the elements in x are rules, eliminate redundancies in the list, and sort the list in a way that increases efficiency. 
A second step would be to implement an ``Atom`` class containing the compiled patterns and modify Replace and ReplaceAll to handle this kind of object.

adding Dispatch (just for compatibility)

---

CHANGES.rst
mathics/builtin/image.py

As part of my advocacy campaign, I have been adding to the default list of worksheets in the Omnibus Image the examples from "An Elementary Introduction to the Wolfram Language". 
I came across this from https://www.wolfram.com/language/elementary-introduction/2nd-ed/07-colors-and-styles.html and this is an easy fix.
Also as part of advocacy I added Mathics to https://en.wikipedia.org/wiki/List_of_computer_algebra_systems

ColorNegate support for colors

---

mathics/builtin/strings.py

@mmatera the thing I don't know about here is what happens when StringTake is given a bad parameter of some form.

Add StringTake with a string sequence.

---

mathics/builtin/diffeqns.py
mathics/core/definitions.py
test/test_context.py

In this PR, some changes were made in the `Definitions` class, in a way that just by evaluating an undefined symbol name, the symbol gets defined.

And the User said light, and light was made.

---

CHANGES.rst
mathics/builtin/codetables.py
mathics/builtin/strings.py

@mmatera Again not sure what error messages/tests we should have here.  Please advise.
Also, handling `Alphabet`s is probably  a bigger project that we probably need come back to.

Letter number

---

mathics/builtin/assignment.py
mathics/core/evaluation.py
mathics/core/pattern.py
test/helper.py
test/test_assignment.py

This should fix #1259. @rocky, I know that this adds more "hackiness" to the method `assign_elementary`, but other solutions would require a huge re-factory of the Pattern matching system.
Once we have a working version of `assign_elementary` that covers all these weird special cases, I promise to start with the re- factory.

Set with OneIdentity LHS

---

mathics/builtin/__init__.py
mathics/builtin/algebra.py
mathics/builtin/arithmetic.py
mathics/builtin/bessel.py
mathics/builtin/erf.py
mathics/builtin/legendre.py
mathics/builtin/specialfunctions.py
mathics/core/expression.py

This is in preparation for other work I wanted to do and bigger refactoring.
Initially, I was just trying to go over functions that have `NumericFunction` and `ListableFunction` properties.
(BTW in `Select[Names["System`*"], MemberQ[Attributes[#], Listable] &]` has a bug somehwere in it.)
It was helpful to have the names sorted for this purpose so I started doing that in specialfunctions. This was unweildy so I have split out  `legandre.py` and `bessel.py` from `specialfunctions.py`. 
Down the line though I'd like to have a subdirectory of builtins called specialfunctions and then we can also adjust our documentation to track this hierachy.  But even as is, I like the fact that the list in SpecialFunctions is smaller while Bessel functions and Legendre polynomials have their own small …

Split and Sort specialfunctions

---

CHANGES.rst
mathics/builtin/calculus.py

Fix derivatives

---

CHANGES.rst
mathics/builtin/logic.py

Note: there will be futher changes to And when we merge ConditionalExpressions.

Add logical operations: Nand and Nor.

---

mathics/builtin/arithmetic.py

Expand `Arg` to handle `Arg[0]`

Handle Arg[0]

---

CHANGES.rst
mathics/builtin/algebra.py
mathics/builtin/arithmetic.py
mathics/builtin/calculus.py
mathics/builtin/datentime.py
mathics/builtin/inference.py
mathics/builtin/logic.py
mathics/builtin/specialfns/erf.py
mathics/core/expression.py

* `Integrate` now uses ConditionalExpression
* `Integrate` simplifies the Sympy output before return.
* Improved `Simplify` using a predicate evaluator,
* `FullSimplify`
* Add Method option Assumption for `Integrate`, and as a second parameter in `Simplify` and `FullSimplify`
* adding `Assuming`

basic implementation of ConditionalExpression, Assuming and

---

CHANGES.rst
mathics/builtin/system.py
setup.py

* we were not using the psutil return values in reporting values
* make psutil mandatory rather than optional: it appears to work on all
the platforms we support.
* Add new variables/functions to `CHANGES.rst`
Fixes #1256

Go over $SystemMemory and MemoryAvailable[]

---

mathics/builtin/files_io/files.py
mathics/builtin/files_io/filesystem.py
mathics/builtin/files_io/mainloop.py
mathics/core/expression.py
test/data/fortytwo.m
test/test_files.py

* Synchronize `PATH_VAR` to $Path at least before `mathics_open()` is called.
*  Add to_python option string_quotes: boolean. If `False`don't add extra surrounding quotes.
* Remove extra space in list in Main Loop doc
Partially addresses https://github.com/mathics/Mathics/issues/1329

Fix a number of small bugs

---

CHANGES.rst
mathics/builtin/lists.py

And run black over the file.
Fixes #1302

More Cases Heads option handling

---

mathics/builtin/files_io/files.py

Small things noticed in looking over #1242
* `SymbolEndOfFile = Symbol("EndOfFile")`
*  Go over Read documentation

Add symbol end of file

---

.github/workflows/osx.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
Makefile
mathics/builtin/logic.py
requirements-dev.txt

specify testing pips and have a way to run pytest in parallel

---

mathics/builtin/inference.py
test/test_assumptions.py

This is the rebase of #1328. In master, there is just a basic version of this.

Advanced predicate processing

---

mathics/builtin/base.py
mathics/builtin/patterns.py

This PR avoids Mathics crashes as in https://github.com/mathics/Mathics/issues/1174#issuecomment-830236513
due to a malformed `Pattern` expression like `MatchQ[3, Pattern[Pattern[a, Blank[]],Blank[]]]`

catch malformed Pattern

---

mathics/builtin/numbers/constants.py

Is this consistent with wolframscript?

Adjust Degree test

---

mathics/builtin/drawing/graphics3d.py
mathics/builtin/graphics.py
mathics/builtin/inout.py
mathics/core/definitions.py
mathics/core/formatter.py
mathics/formatter/svg.py
setup.py
test/test_formatter.py

@mmatera Please look over this approach as a way to better organize, modularize and test formatting primitives.
This was all the time I have on this today.  There probably is a slicker way to do this using Python class inheritance, and do doubt there are ways to reduce tedium of adding methods to a dictionary.
However, this kind of a approach where a step in the right direction.

Start to split off formatting routines..

---

mathics/builtin/base.py
mathics/builtin/fileformats/htmlformat.py
mathics/builtin/inout.py
mathics/builtin/lists.py
setup.py

I tried using the html module but the existing code is too tied in with ElementTree. A separate issue #1382 has been filed to track this aspect.
This is the merge of PRs #1379 and #1380. It fixes #1378.
Changes:
Change setup.py so that lxml is not required
Adjust pyimport error message
Avoid cascading failures in Import
parse_xml_stream(f) is not a usable replacement for HTML, so skip HTML if lxml isn't available

Make Python package lxml optional

---

mathics/builtin/numbers/constants.py

{MPMath,Numpy,Sympy}Constant are include a _ at the beginning now.
This will also clue doc generation not to include them in user-facing docs.

Make internal Builtins internal.

---

mathics/builtin/graphics.py
mathics/doc/tex/Makefile
mathics/formatter/svg.py
test/test_formatter/test_svg.py

Originally I had this as a hack on svg formatting. Then I saw that asymptote formatting was broken too. 
The basic problem is that PointBox doesn't handle PointSize as 0-width points. But the formatters, naturally fill in a nonzero point width. This causes points to extend outside of the viewport for SVG.
PointSize is specified as a fraction of the image width and we might not always have that. And for PointBox we don't have access to the top-level graphics options.
A lot of this should be (re)thought out or documented if it already is. 
Either way once you start to disentangle the code, a lot of the weaknesses become apparent.
Fixes #1091

Handle PointSize in PointBox  (roughly)

---

mathics/builtin/system.py

Not setting MemoryAvailable and SystemMemory was causing MathicsDjango's "about" to fail. 
This then adjusts things accordingliy. <strike>In the process I've added constant -1.</strike> Reverted the Integer(-1) changes because there were mysterious CI problems. 
@TiagoCavalcanteTrindade ^^^^

Handle missing psutil better

---

mathics/builtin/drawing/graphics3d.py
mathics/builtin/graphics.py
mathics/formatter/asy.py

This adds `.to_json()` and `.to_js()` methods to Graphics3DBox objects so that the front end use these without being embedded inside MathML tags. (Of course it is still possible using `to_mathml()` to have these embedded in MathML which may is still used when we have a series of 3D Graphics in a list.)
`to_json()` gives a string representation of a JSON structure which represents the 3D Graphics. TODO: we need to write and API description for what can go in there. However for now what is in mathics.js in Mathics Django will have to do as an operational description.
`to_js()` is probably a bit of a misnomer, but I can't think of a better name. This just wraps the JSON inside a tag called `<graphics3d>`.

Json graphics

---

mathics/builtin/control.py

The tests of `Throw` and `Catch` were written like: `<< test` not `>> test`.
Also shouldn't #1009 be closed?
Maybe #904 too?

Fix Throw and Catch tests

---

mathics/builtin/box/graphics3d.py
mathics/builtin/drawing/graphics3d.py
mathics/builtin/graphics.py
mathics/builtin/lists.py
mathics/core/definitions.py
mathics/core/expression.py
mathics/core/streams.py
mathics/format/asy.py
mathics/format/json.py
test/test_importexport.py

Rebase of #1450.
Closes #1294.

Add Cylinder function

---

mathics/builtin/graphics.py

@rocky #36 is done, but the behavior of `Show` looks strange to me (it shows the list of graphics and the options too).
Also, shouldn't #301, #662, #712, #715, and #717 be closed?

Improve 'Show' documentation

---

mathics/main.py
test/data/script.m
test/test_cli.py

Fix weird results when combining -script and -e

---

mathics/builtin/arithmetic.py
mathics/builtin/numbers/calculus.py
mathics/docpipeline.py
mathics/main.py

@TiagoCavalcanteTrindade  This was a lot messier than I had imagined.  And our system of setting the method of evaluation needs to be redone. And there were bugs outside of just the Factorial2 code. 
Fixes #683

Factorial2 and rough fix some misc bugs

---

mathics/autoload/formats/Asy/Export.m
mathics/builtin/files_io/filesystem.py
mathics/builtin/files_io/importexport.py

@rocky : This would be a very basic implementation of the exporter. This works both to produce a string (what you want here->https://github.com/Mathics3/mathicsscript/pull/44) and to export to a file.
Examples:
```
In[9]:= ExportString[Graphics,"asy"]
Out[9]:= "
usepackage(\"amsmath\");
size(6.6667cm, 2.9762cm);
label(\"$\text{Graphics}$\", (200.0,89.28571428571429), (0,0), rgb(0, 0, 0));
clip(box((172,76.786), (228,101.79)));
"
In[10]:= ExportString[Graphics[{Disk[]}],"asy"]
Out[10]:= "
usepackage(\"amsmath\");
size(5.8333cm, 5.8333cm);
filldraw(ellipse((175,175),175,175), rgb(0, 0, 0), nullpen);
clip(box((0,0), (350,350)));
"
```

Asy exporter

---

mathics/builtin/__init__.py
mathics/builtin/arithmetic.py
mathics/builtin/functional.py
mathics/builtin/intfns/__init__.py
mathics/builtin/intfns/combinatorial.py
mathics/builtin/intfns/divlike.py
mathics/builtin/intfns/recurrence.py
mathics/builtin/numbers/numbertheory.py
mathics/builtin/procedural.py
setup.py

control.py was renamed procedural.py

Reorganize integer functions.

---

mathics/doc/documentation/1-Manual.mdoc
mathics/doc/documentation/A-License.mdoc

Will probably need several more iterations in the future.

Go over docs yet again.

---

mathics/format/json.py

@TiagoCavalcanteTrindade FYI - we should keep compatibility with the older "color" field until Mathics Django is converted. 
Things seem broken when this is embedded in MathML mode. You will see this in the doc examples.

Add opacity field in compact Graphic3D JSON

---

mathics/format/svg.py
test/test_formatter/test_svg.py

Back in a less-hacky way and where we *describe* what's up.
Looks are a little ugly but can probably be fixed using rectangular gradients described in comments in density_plot_box().
Also, we now produce more human-readable SVG. Since this is produced by hand, it is useful to facilitate humans debugging this.

Reinstate Density plot for SVG - rough cut

---

mathics/format/asy.py

In our example, asymptote was formatting:
Graphics[{Blue, Disk[{0, 0}, {1, 2}, {Pi / 3, 5 Pi / 3}]}]
incorrectly because ArcBox didn't support elipses, in Asymptote.

Support elliptic arcs in asymptote

---

MANIFEST.in
admin-tools/make-dist.sh
mathics/doc/common_doc.py
mathics/doc/tex/Makefile
mathics/doc/tex/doc2latex.py
mathics/docpipeline.py
mathics/settings.py
mathics/version.py
setup.py

We now keep both a version of the internal docs for LaTeX formatting in both package space and user space.
User space is writable and can be updated with additional modules as might be found in PyMathics modules one day
The system space is a fallback and is supplied by the distribution. It has document data at the time the distribution was packaged.
Note that data destined for HTML needs to be separate.
The main difference is that the output results format are different: LaTeX/asymptote versus HTML/MathJax/ThreeJS.
Simple, huh?

Revise doc data for TeX

---

mathics/session.py
test/test_settings.py

When we don't have a setting defined, session.get_settings should return
None.

Fix bug in session.get_settings()..

---

mathics/doc/tex/.gitignore
mathics/doc/tex/Makefile
mathics/doc/tex/doc2latex.py
mathics/doc/tex/mathics.tex

Include  the Mathics core version number in the title.
The styling may not be perfect, but I'll leave this for someone who feels more strongly about it, and is willing to hack LaTeX to get it done.

Add Mathics Core version to PDF title

---

mathics/format/json.py

I tested and it is working.
Anyway, I didn't see `rgb_color` being used in `graphics3d.js` ever before.

Rename `rgb_color` to `color`

---

mathics/builtin/numeric.py
test/test_numeric.py

* Put builtins in alphabetic order
* Add summary text for some built ins
* No hard line breaks on doc text
* Move non-showing test code in Rationalize out to a pytest

Mostly cosmetic revision of numeric.py

---

mathics/builtin/patterns.py

Related to #1560, the processing of some typical `PatternTests` that appear in the definitions can be accelerated by evaluating them inside the method `quick_pattern_test`. Here I added a couple.

adding some quick pattern tests for PatternTest

---

mathics/builtin/arithmetic.py

The benchmark:
```
Mathics git repo /workspaces/mathics-benchmark/Mathics at 58dc69
10000 iterations of Rational...
1.312635 secs for: Rational[10, 1]                         
1.235519 secs for: Rational[2, 3]                          
Mathics git repo /workspaces/mathics-benchmark/Mathics at b9b11b
10000 iterations of Rational...
1.199198 secs for: Rational[10, 1]                         
1.159303 secs for: Rational[2, 3]
```
Way more important than that tenth of second is that there is a lot of places where instead of `.to_sympy()` we could use the faster `.value`.

Improve Rational performance

---

CHANGES.rst
mathics/benchmark.py
mathics/builtin/arithmetic.py
mathics/builtin/base.py
mathics/builtin/comparison.py
mathics/builtin/datentime.py
mathics/builtin/inference.py
mathics/builtin/intfns/divlike.py
mathics/builtin/lists.py
mathics/builtin/moments/basic.py
mathics/builtin/numbers/algebra.py
mathics/builtin/numbers/calculus.py
mathics/builtin/numbers/numbertheory.py
mathics/builtin/numbers/randomnumbers.py
mathics/builtin/numeric.py
mathics/builtin/patterns.py
mathics/builtin/procedural.py
mathics/builtin/recurrence.py
mathics/builtin/sparse.py
mathics/core/definitions.py
mathics/core/expression.py

This PR keeps from #1569 those changes related to `N` and `NumericQ`.
Now, 
* NumericQ uses the definitions instead of just a subset of predefined numeric functions.
* A bug in the `Definitions.__init__` method was corrected, which allows distinguishing rules of the form `N[expr_]:=(definition)` of other definitions.
* `Expression("N",expr_,prec_).evaluate(evaluation)` now is a function that avoid to pass through the pattern matching based calling way.

Faster numericq

---

mathics/core/expression.py

We are in the process of preferring Unicode symbols over custom WL
symbols on input (when they are different) since our frontends
use standard Unicode when they support Unicode.

Tolerate Unicode DifferentialD
