- mathics/builtin/numeric.py
- mathics/core/numbers.py
Not much to say about this other than I feel a bit stupid for not testing this in the first place!
> Fix IntegerDigits[0] crash

- mathics/web/media/js/mathics.js
Requested on the issue. Looks like it provides some useful features, like equation zooming.
> Enable MathJax menu (issue #224)

- CHANGES.rst
- mathics/version.py
> Mathics 0.8

- mathics/builtin/comparison.py
Not completely sure about returning None to stop an infinite evaluation loop - if there's a better way I've missed it'd be great to hear about it
> Handle Min/Max with symbolic arguments

- mathics/builtin/control.py
Just another small fix along the lines of the Min/Max one
> Handle Which with symbolic conditions

- mathics/builtin/structure.py
Fix bug raised by @wolfv in the discussion of #268
> fix Flatten bug with non-List head

- mathics/builtin/linalg.py
- mathics/builtin/lists.py
Added Norm.
I had to modify to_sympy_matrix or rather matrix_data to also accept lists (ie. vectors, which are also matrices in sympy).
Not sure if this has unintended consequences. 
Cheers,
Wolf
> Vector norm

- mathics/builtin/lists.py
Something went wrong with the last pull request, but this is a hopefully cleaner version. 
Cheers,
Wolf
> Reopening #252

- .travis.yml
- mathics/builtin/importexport.py
- mathics/core/expression.py
- mathics/doc/documentation/1-Manual.mdoc
- mathics/server.py
- setup.py
- test/test_console.py
- test/test_convert.py
- test/test_parser.py
**`django>=1.7` requires `python>=2.7`**
~~Causes warning messages 1_6W001 and 1_6W002 when creating the database files. Possibly~~ false positives see django tickets [23469](https://code.djangoproject.com/ticket/23469) and [23765](https://code.djangoproject.com/ticket/23765).
> upgrade to django1.8 (and drop python2.6)

- mathics/builtin/arithmetic.py
> Use sympy.conjugate and mpmath.conj for Conjugate

- mathics/server.py
- mathics/settings.py
minor clean-up of a few Django related things
> Django cleanup

- mathics/server.py
> add main funciton to server.py - fixes #288

- mathics/builtin/plot.py
- Fill in a placeholder doc comment
- Set AspectRatio->1 by default to match Mathematica
> Small PolarPlot tweaks

- mathics/main.py
> fix Quit IndexError bug

- mathics/core/evaluation.py
> remove ' | ' added to Print[]

- mathics/core/parser.py
parser bug fixes from over 1 year ago!
> parser fixes

- mathics/builtin/plot.py
Fix a bug in ParametricPlot introduced by b40f6e16ed099061ddcde7b0b270776a75efa4e8
> fix ParametricPlot bug

- mathics/core/evaluation.py
@bnjones @poeschko I'm wondering if either of you have thoughts on this. I've tested it with the django style `manage.py runserver` and it appears to work well.
There doesn't seem to be a noticeable performance difference compared to the signals approach.
> threading solution to #158

- mathics/builtin/importexport.py
reported here: https://groups.google.com/forum/#!topic/mathics-users/9X4GAbWI198
> fix svg Export

- AUTHORS.txt
- CHANGES.rst
- mathics/version.py
- setup.cfg
- setup.py
> Mathics 0.9

- mathics/builtin/inout.py
- mathics/builtin/tensors.py
> Fix TableForm and Dimensions with an empty list

- mathics/builtin/__init__.py
- mathics/builtin/manipulate.py
- mathics/core/evaluation.py
- setup.py
Extension of #362 (since @poke1024 is on vacation).
> Manipulate

- mathics/core/expression.py
Mathics should quit early when looking rules: if a matching rule has been found and applied, no further rule lookups need to happen.
This seems to improve performance by 10% generally, might be much more dramatic in certain cases.
> shortcut rule lookup

- mathics/builtin/linalg.py
> QRDecomposition

- mathics/core/expression.py
- test/test_arithmetic.py
This is a follow up of the previous arithmetic PR without the assumption that arithmetic functions should be hard coded. As it turns out, Plus and Times can be overridden in MMA. So this PR is just some conservative syntactic sugar for expression construction.
> Magic methods for Expression

- mathics/builtin/lists.py
> fix Take[_Symbol, ___]

- mathics/builtin/strings.py
> HammingDistance[]

- mathics/builtin/linalg.py
_norm_diff tries to model MMA's behaviour when you pass parameters that are not compatible
> EuclideanDistance[] and related

- mathics/builtin/combinatorial.py
An implementation for the most dissimilarity measures
> JaccardDissimilarity and others

- mathics/algorithm/__init__.py
- mathics/algorithm/introselect.py
- mathics/builtin/lists.py
- setup.py
This introduces linear time selection capabilities based on introselect (https://en.wikipedia.org/wiki/Introselect).
I implemented introselect from scratch, since the only two implementations I'm aware of (one in C++'s STL and one inside numpy's argpartition) seem quite cryptic to me in regards to certain steps, and - apart from licensing issues - a Python port of these would have been even more cryptic. For the most part, I just implemented Hoare's old algorithms as described in the 1960 ACM publication without any changes, and, indeed, they work.
Having a reliable median implementation is an important stepping stone for implementing something like kdtrees later on.
The new package "algorithm" is of course just a proposal: for functions implementing basic algorithms and data structures …
> Median[], RankedMin[], RankedMax[]

- mathics/algorithm/introselect.py
- mathics/builtin/assignment.py
- mathics/builtin/calculus.py
- mathics/builtin/comparison.py
- mathics/builtin/files.py
- mathics/builtin/integer.py
- mathics/builtin/linalg.py
- mathics/builtin/numbertheory.py
- mathics/builtin/numeric.py
- mathics/builtin/numpy_utils.py
- mathics/builtin/plot.py
- mathics/builtin/randomnumbers.py
- mathics/builtin/specialfunctions.py
- mathics/builtin/structure.py
- mathics/builtin/system.py
- mathics/core/definitions.py
- mathics/core/evaluation.py
- mathics/core/expression.py
- mathics/core/rules.py
- mathics/main.py
ran flake8 and found some typos.
> some code cleanups

- mathics/builtin/randomnumbers.py
fixes #406
also fixes a bug in `RandomComplex`.
> Legacy Random function

- .pep8
- mathics/builtin/arithmetic.py
- mathics/builtin/base.py
- mathics/builtin/calculus.py
- mathics/builtin/comparison.py
- mathics/builtin/inout.py
- mathics/builtin/patterns.py
- mathics/core/expression.py
remove some unused code from the original (very old) parser.
> Cleanup parser

- setup.py
see https://github.com/mathics/Mathics/issues/418
I also removed the PyPy numpy stuff, since it's not usable right now anyway.
> remove numpy dependency from setup.py

- mathics/core/convert.py
Just some stuff left over from Sage that we're not using any more
> Remove unused code from convert.py

- mathics/builtin/arithmetic.py
> implement Indeterminate using sympy.nan

- mathics/builtin/base.py
- mathics/builtin/lists.py
- mathics/core/expression.py
some minor parser related cleanups
> Parser cleanups

- mathics/builtin/integer.py
I noticed some strange performance regressions in `IntegerLength`.
Traced this down to an intermittent bug in sympy: https://github.com/sympy/sympy/issues/11414
Here's a workaround.
> optimise IntegerLength

- mathics/builtin/control.py
- mathics/builtin/lists.py
- mathics/builtin/structure.py
- mathics/core/evaluation.py
essentially a copy of `Map` but returns `Null`.
> implement Scan and Return

- mathics/builtin/arithmetic.py
- mathics/builtin/diffeqns.py
- mathics/builtin/exptrig.py
- mathics/builtin/linalg.py
- mathics/doc/documentation/1-Manual.mdoc
Some cleanups refactored out of #463.
> Cleanup power

- mathics/builtin/inout.py
- mathics/core/evaluation.py
Had to be a bit careful to preserve the set of quiet messages between evaluations.
> implement On and Off

- mathics/builtin/calculus.py
fixes what looks like a typo to me
> typo in Derivation[]?

- mathics/builtin/integer.py
> Fix typo + add test for FromDigits::nlst

- mathics/builtin/numeric.py
- mathics/core/numbers.py
Tests failing because of #448.
> implement $MachineEpsilon and $MachinePrecision

- mathics/main.py
- setup.py
The installer was not setting up the Django database; this should fix it.
Note that one can still manually set up the database by running `python setup.py initialize`.
> Fix #382: issues with saving and loading notebooks in web interface

- mathics/builtin/lists.py
I thought I had an PR on this, but I hadn't. So here it is.
> PadLeft, PadRight

- mathics/web/media/js/mathics.js
Reverts mathics/Mathics#490
This innocent looking change broke the web front-end.
> Revert ".nodeValue deprecated in favour of .value"

- mathics/builtin/exptrig.py
- mathics/builtin/image.py
- mathics/builtin/linalg.py
> Image fixes

- mathics/builtin/lists.py
Basic (i.e. only support for vectors), but still very useful
> Basic versions of Covariance, Correlation

- mathics/core/expression.py
Not a measurable performance improvement, but maybe cleaner?
> Restructuring of eval_range code

- mathics/builtin/graphics.py
- mathics/builtin/lists.py
Adds support for `Cases` replacement rules and level spec.
> Cases extensions

- mathics/core/evaluation.py
Provides better error messages in the console:
```
In[1]:= 1 / 0
Power::infy: Infinite expression 1 / 0 encountered.
Out[1]= ComplexInfinity
```
> better messages

- mathics/builtin/lists.py
- mathics/builtin/strings.py
- clean-up and extend`StringTake` to use proper sequence spec. code.
- fix some `Take` edge cases also affecting `StringTake`.
> Take edge cases

- mathics/builtin/graphics.py
Currently, in `Graphics[]`, it's not possible to add options with `Style[]`.
So, `Graphics[Style[Text[1], Red]]` is possible, but `Graphics[Style[Text[1], FontColor -> Red]]` is not.
This PR adds the infrastructure for parsing `Style[]` options and also adds `FontColor` as a first example.
> Adds options to Style[]

- mathics/builtin/graphics.py
Allows for `Graphics[Circle[], Background -> Blue]`
> Background option for Graphics

- mathics/builtin/inout.py
fixes some `NumberForm` edge cases.
> NumberForm edge cases

- mathics/builtin/assignment.py
- mathics/core/expression.py
Also fixes a bug introduced by #535.
> optimise expression creation

- mathics/builtin/image.py
These language codes are the same ones as in https://github.com/mathics/Mathics/pull/472. Some common place to put them would be good.
> TextRecognize[]

- mathics/builtin/graphics.py
This PR aims to increase coverage of ColorDistance function. 
It lacks check for mandatory option after the arguments (see #547)
> ColorDistance enhancements

- mathics/builtin/importexport.py
For example, you can now use:
`Import["https://blogs.nasa.gov/spacestation/wp-content/uploads/sites/240/2016/08/blog_iss048e061947.jpg"]`
> Add download from URL to Import[]

- mathics/builtin/importexport.py
Fix for https://github.com/mathics/Mathics/issues/562
> Python2 Import[] fix

- mathics/builtin/lists.py
In contrast to `Gather`, `GatherBy` had quadratic runtime until now. This changes it to linear.
> Make GatherBy efficient

- mathics/builtin/image.py
- Images with alpha channels are now displayed correctly
- Loading jpegs with missing exif data no longer crashes
> Two bug fixes for images

- mathics/autoload/formats/XML/Import.m
- mathics/builtin/xmlformat.py
- mathics/data/ExampleData/Namespaces.xml
- mathics/data/ExampleData/copyright.csv
Import from file/url now works properly (default importer was missing from `XML/Import.m`)
Namespaces are now supported and handled as in MMA (added a test case for this)
> Fixes two problems with XML imports

- mathics/builtin/natlang.py
Basically https://github.com/mathics/Mathics/pull/593 with a few tricks to not break anything
> Fix for nltk loading problem

- mathics/builtin/linalg.py
There's no nice formatting of `FittedModel` yet, but all the data is there.
Depends on https://github.com/mathics/Mathics/pull/591.
> Adds LinearModelFit

- mathics/builtin/calculus.py
- mathics/builtin/diffeqns.py
- mathics/core/convert.py
- test/test_convert.py
Some cleanups to reflect changes to sympy's `dsolve`. Adds support for PDE.
> DSolve for PDE

- mathics/builtin/graphics.py
- mathics/builtin/xmlformat.py
- mathics/core/expression.py
- mathics/doc/doc.py
- mathics/doc/documentation/A-License.mdoc
- mathics/doc/images.sh
- mathics/doc/tex/mathics.tex
some fixes to get the docs building again
> Mathics 1.0 doc fixes

- mathics/builtin/importexport.py
Stuff like Import["http://someurl", CharacterEncoding -> "ISOLatin1"] works now (was broken before).
> Fixes FetchURL options

- mathics/builtin/comparison.py
- mathics/builtin/strings.py
Add BooleanQ, DigitQ, LetterQ
This is my first pull request. It is great if you guys can spend sometime to feedback on this. Thank in advance
> Adding some checking functions

- mathics/builtin/algebra.py
PolynomialQ and MinimalPolynomial are implemented in this PR
> Polynomial functions

- mathics/builtin/linalg.py
Implements the basic form of [Tr](http://reference.wolfram.com/language/ref/Tr.html.en) (trace of a square matrix).
> Add matrix trace as Tr

- mathics/builtin/arithmetic.py
> fix conversion of complex inf

- .travis.yml
- mathics/builtin/arithmetic.py
- mathics/builtin/calculus.py
- mathics/builtin/combinatorial.py
- mathics/builtin/comparison.py
- mathics/builtin/image.py
- mathics/builtin/linalg.py
- mathics/builtin/lists.py
- mathics/core/convert.py
- setup.py
- test/test_convert.py
This fixes #718 
There was a missing match for String List equality and the empty slice was not implemented for all cases.
> add string list comparison and empty slice

- mathics/builtin/lists.py
This pull request for adding function FirstPosition to Mathics
> Add FirstPosition

- mathics/builtin/lists.py
This pull request for adding LeafCount function
> Add LeafCount

- mathics/builtin/__init__.py
- mathics/builtin/optimization.py
Hello,
I'm making my first contribution to Mathics project giving symbolic optimization support.
> Minimize and Maximize support

- mathics/builtin/natlang.py
Let's see if that's enough to fix the travis issue, or if we need the medium sized model.
> download new spacy model on travis

- .travis.yml
- mathics/settings.py
- mathics/urls.py
- mathics/web/templates/base_html.html
- mathics/web/urls.py
- mathics/web/views.py
- setup.py
Resurrecting https://github.com/mathics/Mathics/pull/677
> Django 1.11

- .travis.yml
- mathics/builtin/__init__.py
- mathics/builtin/quantities.py
This pull request to adding Quantity and its related functions:
- KnownUnitQ
- UnitConvert
- Quantity
- QuantityQ
- QuantityUnit
- QuantityMagnitude
> Add function Quantity and its related functions

- mathics/builtin/algebra.py
- mathics/builtin/optimization.py
> Fix most incompatibilities with the Diofant

- .travis.yml
This is a follow up to https://github.com/mathics/Mathics/issues/810.
> Included scikit-image in .travis.yml

- .gitignore
- .travis.yml
- mathics/builtin/base.py
- mathics/builtin/inout.py
- mathics/core/definitions.py
- mathics/core/evaluation.py
- mathics/core/expression.py
- mathics/core/numbers.py
- mathics/core/rules.py
- mathics/core/util.py
- setup.py
The situation with static typing in Python is very far from perfect, but I still hope that some types will make Mathics more maintainable.
> Add some types

- mathics/builtin/calculus.py
- mathics/builtin/numeric.py
Also fixed a bunch of errors in `Root`'s `to_sympy` implementation
> Made it so that N computes approximation of polynomial roots

- mathics/builtin/algebra.py
Implemented functionality marked as TODO in the `Expand` builtin.
> Expanded Expand

- mathics/builtin/calculus.py
- mathics/builtin/functional.py
- mathics/core/expression.py
Now `Expression.replace_slots` takes associations into account
> Fixed the bahaviour of `Expression.replace_slots`

- mathics/builtin/randomnumbers.py
This is a follow up to https://github.com/mathics/Mathics/issues/744#issuecomment-687595662
> Implemented randchoice for NoNumPyRandomEnv

- AUTHORS.txt
- mathics/__init__.py
@suhr I've added you to the list of contributors too.
> Updated the information about licensing and contributors

- mathics/test.py
Also show number within section.
Before:
```
1. TEST 1 + 2
2. TEST 1 - 2 * (3 + 5) / 4
3. TEST 1 - 2 (3 + 5) / 4
...
```
Now:
```
**********  Language tutorials / Basic calculations **********
1 ( 1): TEST 1 + 2
2 ( 2): TEST 1 - 2 * (3 + 5) / 4
...
**********  Language tutorials / Symbols and assignments **********
25 ( 1): TEST x
26 ( 2): TEST x + 2 x
```
> Show chapter/sections in test.py

- mathics/core/definitions.py
> Fixed bug in Quit[]

- .travis.yml
- mathics/benchmark.py
- mathics/builtin/datentime.py
- mathics/builtin/files.py
- mathics/builtin/numpy_utils/with_numpy.py
and with this mathics can get to a 3.8 `In[]` prompt.
This is not the most elegant or efficient code, but it works.
> Python 3.8, 3.9 and Pypy 3.6 compatability

- mathics/builtin/physchemdata.py
- mathics/settings.py
Fixes https://github.com/mathics/Mathics/issues/847.
> Fix django

- setup.py
We no longer support 3.4 and 3.5, and do support 3.7 and 3.8
blacken setup.py
> Update PyPI Python index for supported version

- .travis.yml
- mathics/builtin/plot.py
- mathics/packages/Combinatorica/Combinatorica.m
- mathics/packages/Combinatorica/Kernel/init.m
- setup.py
This works and is cool. More work will come down the line to remove various errors.
Fixes #733
> Add Combinatorica Package

- mathics/builtin/system.py
- mathics/core/definitions.py
BTW this points out a flaw in that we have older Combinatorica code.
That will be corrected in another PR.
> Add $Package

- .travis.yml
This is better matched for newer software. 
Although we may use Github actions as well, there is no reason not to have 2 or even 3 kinds of CI. (I often use 3 in my other projects: TravisCI, CircleCI and Appveyor)
> Travis ci focal

- .github/workflows/basic.yml
- .travis.yml
- README.rst
- setup.py
- test/test_arithmetic.py
What started as a simple commit to fix README.rst has morphed into a github flows revamp.
I could and should probably split this into to separate PRs. 
RsT Get code blocks tagged correctly now.
> Github actions  and Mark iwolfram as experimental for now

- .travis.yml
- Makefile
- mathics/doc/tex/Makefile
- mathics/test.py
This is a follow up to https://github.com/mathics/Mathics/issues/840#issuecomment-692163808.
> Fixed missing file error in write_latex()

- .travis.yml
- mathics/builtin/numeric.py
In this pull request, the RealDigits[] function has been added to the Mathics.
In order to pass all the TravisCI checks, I've also updated the .travis.yml file by adding the package Requests and specifying the version of Ipython to 5.0.0.
> Add RealDigits

- COPYING.txt
- mathics/builtin/importexport.py
- mathics/doc/documentation/1-Manual.mdoc
- mathics/web/templates/base.html
This is a follow up to https://github.com/mathics/Mathics/issues/762. I removed all references I could that point to www.mathics.net.
> Remove most references to mathics.net and mathics.org

- CHANGES.rst
- mathics/builtin/__init__.py
- mathics/builtin/datentime.py
- mathics/builtin/evaluation.py
- mathics/core/expression.py
TimeZone (what was there before) isn't protected and can be changed
SystemTimeZone can't be changed. It is the thing that TimeZone acted
like previously.
There is also some small lint-like things of other files.
> Add SystemTimeZone, adjust TimeZone..

- CHANGES.rst
- mathics/Makefile
- mathics/builtin/system.py
Add `Environment[]` and `Environment[rule]`
Also: 
in `mathics/Makefile`  - transfer  "check" call
> Add Environment[name] and Environment[]

- mathics/core/evaluation.py
- mathics/core/parser/util.py
This allows CLI's with history tracking to be able to do the more
sensible thing and group multiple lines as one item.
It also will make it possible for better error reporting.
> Allow passing back source-code lines..

- Makefile
- mathics/web/urls.py
- mathics/web/views.py
- setup.py
urls.py: blacken
setup.py: remove not necessary dependencies
- colorama is optional as it was in 1.0
- pyplot was part of graphs. It will appear in a depencency in the
corresponding graphs pymathics module
views.py: remove some unused imports
> 4 small tweaks:

- mathics/builtin/files.py
- mathics/builtin/importexport.py
- mathics/doc/doc.py
Fixes https://github.com/mathics/Mathics/issues/946.
> Disable some tests

- mathics/builtin/assignment.py
- mathics/builtin/base.py
- mathics/builtin/evaluation.py
- mathics/builtin/importexport.py
- mathics/web/views.py
I don't understand why we had an Exit doesn't exit and is an alias for Quit. 
It is very useful in testing to have a real Exit from Mathics with a return code.
> Exit exits Mathics; it can set return code too.

- mathics/builtin/assignment.py
- mathics/builtin/files.py
- mathics/builtin/importexport.py
Fixing the load of modules from URLs
> fixing Import@

- mathics/builtin/files.py
This PR fixes the tests for Get and Put, by using $TemporaryDirectory as the root for temporary files.
> fix Get/Put test

- test/test_evaluation.py
- test/test_file.py
Just basic tests for these functionalities
> adding tests for  Exit,Quit and file operations

- Makefile
- mathics/builtin/compilation.py
- mathics/builtin/inout.py
- mathics/doc/doc.py
- mathics/doc/tex/Makefile
Reduce duplicate testing in building docs. Simplify
> Doc building simplify

- mathics/builtin/algebra.py
- mathics/builtin/arithmetic.py
- mathics/builtin/calculus.py
- mathics/builtin/combinatorial.py
- mathics/builtin/control.py
- mathics/builtin/specialfunctions.py
- mathics/builtin/strings.py
- mathics/builtin/system.py
- mathics/builtin/tensors.py
- mathics/web/media/js/inout.js
Start to regularize capitalization in title names and align better
with Mathematica 5 names. (MMA 5 is the book I have laying around).
One 3D gallery example replace with perhaps a better one. 
blacken another file. Make some files not sensitive to trailing blanks.
> Go over section titles; add $UserName

- test/test_evaluation.py
Some minimal tests for functions in the "Global System Information" section. 
Dedicated to Juan Mauricio Matera who requested them.
> Add pytests for Global System Information section

- .gitignore
- mathics/builtin/comparison.py
Closes #956
This is a cleaner #998.
I think this PR is ready to be merged.
> Symbolic comparisions

- CHANGES.rst
What's up with #1001 and #1003
> Update CHANGES.rst for #1003 and #1001

- mathics/builtin/lists.py
- test/test_deletecases.py
This PR fix issue #1010, related to #995.
> Improvedeletecases

- mathics/core/expression.py
This would be a fix for issue #1014
> adding support for bool in from_python

- mathics/builtin/compilation.py
@rocky  this should fix issue #1024, until a better solution comes up
> fix compile

- mathics/builtin/files.py
- mathics/core/parser/feed.py
`Get["fn", Trace->True]` will show lines as they are read.
This isn't ideal, but it is a start. I would also like to do the same for Import.
> Add Trace option to Get

- mathics/core/evaluation.py
Here, the front-end will handles formatting.
> Allow for unformatted results

- mathics/builtin/control.py
- mathics/builtin/files.py
- mathics/builtin/scoping.py
- mathics/core/evaluation.py
- mathics/packages/DiscreteMath/CombinatoricaV0.6.m
- mathics/packages/DiscreteMath/Kernel/init.m
- test/test_control.py
Since this is based on #1025 we whoudl merge only after that lands on master.
> Combinatorica again

- mathics/core/parser/operators.py
- mathics/core/parser/tokeniser.py
I think this is what is needed to add DirectedEdge, but please correct if this is faulty. 
(DirectedEdge starts to appear when specifying graphs).
> Add DirectedEdge

- mathics/core/parser/tokeniser.py
This branch was merged into master but it has a bug in handling undirected edges. This should fix that.
> Had broken <-> for UndirectedEdge

- mathics/builtin/arithmetic.py
- mathics/builtin/calculus.py
- mathics/builtin/combinatorial.py
- mathics/builtin/comparison.py
- mathics/builtin/control.py
- mathics/builtin/tensors.py
- mathics/core/expression.py
- test/test_hash.py
There were numerous complicated ways we were tesing for Symbol("True") and Symbol("False"). 
This simplfies the code. Some more files are blackened in the process.
After this is done, probalby Symbol("Null") is next.
> Symbol("True') and Symbol("False')

- .github/workflows/basic.yml
- .travis.yml
- mathics/core/expression.py
- mathics/core/numbers.py
Try speeding up workflows testing using "make -j3"
> Add SymbolNull and try speeding up Workflows testing

- mathics/packages/DiscreteMath/CombinatoricaV0.6.m
- mathics/packages/DiscreteMath/CombinatoricaV0.9.m
- mathics/packages/DiscreteMath/Kernel/init.m
From none other than Prof/Dr Steven Skiena!
> Add Combinatorica V 0.9ish

- .github/workflows/osx.yml
See if we can get OSX testing on github actions
> Try OSX CI on workflows

- mathics/builtin/assignment.py
- mathics/builtin/files.py
- mathics/builtin/importexport.py
- mathics/builtin/lists.py
- mathics/builtin/strings.py
- mathics/builtin/xmlformat.py
- mathics/core/expression.py
And convert some linging Symbol("True") and Symbol("False")
to SymbolTrue, SymbolFalse.
> Symbol("$Failed") -> SymbolFailed

- Makefile
- mathics/builtin/graphics.py
- mathics/builtin/graphics3d.py
- mathics/builtin/plot.py
- mathics/doc/documentation/1-Manual.mdoc
* Disambiguate ambiguous terms like Graphics
* Add docs for PlotPoint, PlotRange, and Filling options
* Note in Graphics what options are available
Also "make check" includes the doc test. It was inadvertently removed.
> Go over graphics docs

- mathics/builtin/exptrig.py
- mathics/builtin/specialfunctions.py
> Add Catalan and LerchPhi

- mathics/builtin/lists.py
- mathics/packages/DiscreteMath/CombinatoricaV0.9.m
- test/helper.py
- test/test_combinatorica.py
These bug fixes were a result of expanding Combinatorica example testing to page 28.
> Start Insert[]. Fix Do[] for negative increment

- mathics/autoload/settings.m
- mathics/builtin/system.py
- mathics/core/definitions.py
Blacken system.py and add more return types.
> Redo MathicsVersion as Predefined

- CHANGES.rst
- mathics/builtin/control.py
- mathics/builtin/datentime.py
- mathics/builtin/lists.py
- mathics/builtin/randomnumbers.py
- mathics/core/evaluation.py
- mathics/core/expression.py
- test/test_datentime.py
- test/test_numpy_utils.py
> Implementing TimeConstrained and TimeRemaining

- mathics/builtin/__init__.py
- mathics/builtin/assignment.py
- mathics/builtin/base.py
- mathics/core/definitions.py
- mathics/core/expression.py
Working in the matplotlib module I found certain deficiencies in the current implementation of LoadModule. Here I put those with the simplest solution.
> Small fixes in the pymathics mechanism 

- CHANGES.rst
@mmatera @GarkGarcia please review and add items I've missed. In the interest of speeding things up, just commit on top of this.
> What's changed since 1.1.1

- mathics/builtin/assignment.py
- mathics/builtin/base.py
- mathics/core/definitions.py
This fixes partially https://github.com/Mathics3/mathicsscript/issues/23
A second problem is that some symbols in the package are not properly loaded. I need to investigate a little bit more...
> fix pymathics context

- CHANGES.rst
Also fix some typos and minor rephrasing.
> Improve formatting in CHANGES

- mathics/builtin/system.py
See https://github.com/mathics/Mathics/pull/1155#discussion_r579784676
> handle os.getlogin failures

- mathics/core/expression.py
Rational numbers are not created if the denominator is zero...
> fix rational is_zero

- mathics/builtin/calculus.py
This PR just fix the way in which Integrate is translated to TeX
> fix TeXForm for Integrate

- mathics/builtin/importexport.py
More fixes to the ByteArray Exporter
> Fix base64 encode

- mathics/builtin/files.py
- mathics/builtin/importexport.py
- test/helper.py
- test/test_files.py
- test/test_inout.py
Lost fixes for ImportExport and Base64
> Fixesimportexportstring

- mathics/builtin/comparison.py
- mathics/core/expression.py
- test/test_compare.py
Handle complex versus real comparisons. 
Fixes #1168
> Exact number comparisions

- CHANGES.rst
- mathics/builtin/combinatorial.py
- test/test_combinatorica.py
Extend combinatorica examples to page 64 or so.
> Add builtin PartitionsP[]

- mathics/builtin/arithmetic.py
- mathics/builtin/base.py
- mathics/builtin/files.py
- mathics/builtin/linalg.py
- mathics/builtin/numeric.py
- mathics/builtin/specialfunctions.py
- mathics/core/expression.py
Memoization isn't haven't a big effect although I do see it is doing something. More important from a maintainablilty
is the blackening of some files and clearification with by starting to rename `apply_2`, etc with more descriptive name and to use
"%(name)s" so that when things move around we don't have to change that.
> More descriptive and general in prep for profiling

- CHANGES.rst
- mathics/builtin/comparison.py
- mathics/builtin/compilation.py
- mathics/builtin/numbertheory.py
- mathics/builtin/numeric.py
- mathics/doc/documentation/1-Manual.mdoc
Include deletion in conjunction of worksheets.
Go over typographical setting in various new docs.
> Make a pass over documents

- mathics/builtin/constants.py
See https://groups.google.com/g/mpmath/c/qzA5gs57Qm8/m/sksRJOGrAAAJ
Should help in with https://github.com/mathics/Mathics/issues/1169#issuecomment-805661065
> Don't use `mpmath.ctx_mp_python.mpf`, but `mpmath.mpf`

- mathics/builtin/arithmetic.py
- mathics/builtin/calculus.py
- mathics/builtin/files.py
- mathics/builtin/graphics.py
- mathics/builtin/graphics3d.py
- mathics/builtin/image.py
- mathics/builtin/importexport.py
- mathics/builtin/inout.py
- mathics/builtin/lists.py
- mathics/builtin/numbertheory.py
- mathics/builtin/numeric.py
- mathics/builtin/patterns.py
- mathics/builtin/plot.py
- mathics/builtin/structure.py
- mathics/builtin/system.py
- mathics/core/convert.py
- mathics/core/definitions.py
- mathics/core/evaluation.py
- mathics/core/expression.py
This is an attempt to reduce the overhead in comparisons and pattern matching. @rocky, could you profile this against master?
> Singletonize Symbols frequently used in Head 

- mathics/builtin/assignment.py
- mathics/builtin/patterns.py
> implementing Conditions in LHS

- mathics/builtin/strings.py
- mathics/core/evaluation.py
- mathics/core/expression.py
- mathics/session.py
- mathics/settings.py
A first try about how ToString should manage the `CharacterEncoding` option (see #1183)
> Add  $SystemCharacterEncoding and CharacterEncoding in boxes_to_text and ToString[]

- mathics/benchmark.py
- mathics/main.py
- mathics/profile_mathics.py
- mathics/session.py
- mathics/settings.py
- mathics/test.py
I forgot to black these files before...
> blacken files in the main directory

- CHANGES.rst
- mathics/builtin/files.py
From #1199:  
* Makes $Path an unprotected variable
* Improve the support for reading expressions from files.
> Improve read expressions

- mathics/builtin/files.py
- test/test_files.py
Note: Unprotect doesn't seem to work for $Path, $InstallationDirectory,
Makeboxes if not others in Django. What's up here?
But let's get this in and continue from here. 
See #90
> Unprotect $InstallationDirectory

- CHANGES.rst
- mathics/builtin/strings.py
> Improve ToExpression parsing of multi-line input

- CHANGES.rst
- mathics/builtin/sparse.py
Basic implementation of SparseArray
TODO:
* Operations between sparse objects.
* Conversion to the format for numeric libraries.
* Optimize the representation of the non-vanishing elements.
> Sparsearray

- CHANGES.rst
- mathics/builtin/files.py
> Sorted file names

- mathics/builtin/files.py
Just removes the warning when Read receives a comment without an expression.
> Processing comments in Read Expression

- COPYING.txt
- mathics/builtin/assignment.py
This also seems to appears frequently on packages. In particular FeynCalc
> support for HoldPattern as lhs in Set

- mathics/builtin/datentime.py
> basic implementation of Now and DateObject

- mathics/builtin/assignment.py
This is another patch to assign_elementary that fixes issue  #1249
> Respect OptionValue inside a Condition (another changet to _SetOperator)

- mathics/builtin/control.py
- mathics/builtin/filesystem.py
- mathics/builtin/strings.py
to something that better expresses the deviation.
I use _with_xx when there is an additional xx parameter
_for is use when the argument type has changed
ColorNegate (for color, for image)
> Convert some non-descriptive apply1 names..

- CHANGES.rst
- mathics/builtin/calculus.py
- mathics/builtin/scoping.py
- test/test_calculus.py
This seems to work.
TODO
---------
* Compile Functions and Derivatives
* Implementing other methods
* Implementing checks in AccuracyGoal  and PrecisionGoal
* FindRoot over vectors (F is a vector, or x0 is a vector)
> fixing FindRoot

- CHANGES.rst
- mathics/builtin/arithmetic.py
This PR adds ``Arg`` based on Sympy. Some extra rules in Mathics add added in order to handle infinity quantities.
> Adding Arg 

- mathics/core/expression.py
Make it easier to spot if something is on the list and if there
are duplicate definitions as there had been before this commit.
> sort predfined Symbols

- CHANGES.rst
- mathics/builtin/arithmetic.py
- mathics/builtin/assignment.py
- mathics/builtin/calculus.py
- mathics/builtin/files.py
- mathics/builtin/logic.py
- mathics/builtin/optiondoc.py
- mathics/builtin/strings.py
- mathics/core/evaluation.py
- mathics/core/expression.py
- mathics/core/parser/operators.py
- mathics/core/parser/parser.py
- mathics/core/pattern.py
- test/helper.py
- test/test_assignment.py
This is a test branch where several PRs related to #1174 in mathics/mathics are merged.
> Feyncalcfixes

- mathics/builtin/strings.py
@rocky, this is how I think the support for different alphabets could work. A maybe still better approach is to use also `dicts` (instead of strings) to store the alphabets. Thoughts?
> support for Alphabets

- test/test_context.py
- test/test_files.py
Reverts mathics/Mathics#1311
Apparently this still has paroblems.
> Revert "fix some tests"

- mathics/builtin/algebra.py
- mathics/builtin/arithmetic.py
- mathics/core/expression.py
* `Arg[0]` needs to be defined 0 (otherwise it can be indeterminate)
* More complete doc for Arg
* Add Method option
> Misc Arg tweaks:

- mathics/builtin/algebra.py
- mathics/builtin/files.py
A couple of `has_form()` uses noticed in going over #1271
> Use has_form() more effectively in a couple of places

- mathics/builtin/strings.py
- mathics/core/expression.py
- mathics/core/parser/operators.py
- mathics/core/parser/parser.py
> fix support for \!

- mathics/builtin/algebra.py
- mathics/builtin/arithmetic.py
- mathics/builtin/attributes.py
- mathics/builtin/calculus.py
- mathics/builtin/combinatorial.py
- mathics/builtin/erf.py
- mathics/builtin/evaluation.py
- mathics/builtin/exptrig.py
- mathics/builtin/filesystem.py
- mathics/builtin/graphics.py
- mathics/builtin/integer.py
- mathics/builtin/lists.py
- mathics/builtin/numbertheory.py
- mathics/builtin/strings.py
up to about Range. Start from about there...
Also expand Attributes to accept a string parameter as it should.
> Go over functions with Listable attribute..

- mathics/builtin/lists.py
This is the fix for the issue #1302
> fix for 1302

- CHANGES.rst
- mathics/test.py
Just another small took for checking performance along the doctests.
> timing individual tests

- mathics/builtin/algebra.py
- mathics/builtin/arithmetic.py
- mathics/builtin/comparison.py
- mathics/builtin/exptrig.py
- mathics/builtin/image.py
- mathics/builtin/integer.py
- mathics/builtin/lists.py
- mathics/builtin/numbertheory.py
- mathics/builtin/numeric.py
- mathics/builtin/plot.py
- mathics/builtin/sparse.py
- mathics/builtin/specialfns/othogonal.py
- mathics/builtin/strings.py
- mathics/builtin/structure.py
- mathics/builtin/system.py
- mathics/builtin/tensors.py
- mathics/core/convert.py
- mathics/core/expression.py
- test/test_parser/test_convert.py
A large number of changes for such as simple thing.
> Integer(0) -> Integer0; Integer(1) -> Integer1

- test/test_files.py
regarding https://github.com/mathics/Mathics/pull/1304#commitcomment-50091588
I adding a test for a (two steps) recursive `Get`
Maybe later we can go over the other more complex tests...
> test $InputFileName in recursive get

- mathics/builtin/__init__.py
- mathics/builtin/drawing/plot.py
- mathics/builtin/graphics.py
- mathics/builtin/lists.py
- mathics/builtin/optiondoc.py
- mathics/doc/doc.py
- mathics/packages/DiscreteMath/CombinatoricaV0.9.m
Reverts mathics/Mathics#1353
I will redo later with fixup to TeX when I get a chance.
> Revert "Doc updates"

- CHANGES.rst
- mathics/autoload-cli/settings.m
- mathics/autoload/settings.m
- mathics/builtin/inout.py
- mathics/core/definitions.py
- mathics/main.py
- setup.py
Needs to be coordinated with https://github.com/Mathics3/mathics-django/pull/41/files
> General autoload

- mathics/main.py
Add double quotes to string output.
> Surround string output in double quotes.

- mathics/settings.py
- mathics/system_info.py
- test/test_system_info.py
- test/test_to_python.py
This will be used for example in the Django front-end's "about"
page.
> Easy access to system information

- CHANGES.rst
- mathics/doc/documentation/1-Manual.mdoc
- mathics/version.py
@mmatera - last chance to review before release. Please look over.
> Get ready for release 2.2.0

- mathics/builtin/drawing/graphics3d.py
- mathics/core/definitions.py
- mathics/formatter/json.py
Which is used right now only by graphics3d
> Add json formatter

- .gitignore
- mathics/builtin/system.py
- requirements-extra.txt
- setup.py
> Make psutil optional - msys doesn't have

- mathics/builtin/drawing/graphics3d.py
@mmatera This is in conjunction with https://github.com/Mathics3/mathics-django/pull/47
I don't know if it is too hacky or if it could be made serviceable. But the basic idea is to have some sort of minimal support for TicksStyle so that something like that PR linked makes more sense.
> TicksStyle 3D

- .gitignore
- mathics/doc/doc.py
- mathics/doc/tex/Makefile
- mathics/settings.py
- mathics/system_info.py
- mathics/test.py
That is now just in the Django copy of this.
This needs to be coordinated with https://github.com/Mathics3/mathics-django/pull/48
> Remove HTML-oriented code.

- mathics/builtin/numbers/algebra.py
- test/test_calculus.py
- test/test_colors.py
Also start adding module docstring for some other unit tests.
> Remove unit tests from algebra module

- mathics/formatter/svg.py
Fixes https://github.com/Mathics3/mathics-django/issues/2
There is larger work needed of being able to specify and pass down the desired point size. And more generally, font parameters and the kinds of parameters allowed by svg.
> Specify SVG text size in InsetBox

- mathics/builtin/drawing/graphics3d.py
- mathics/builtin/graphics.py
- mathics/formatter/svg.py
- test/test_formatter/test_svg.py
Put in alphabatic order some functions in GraphicsBox and Graphicss3DBox
and add some docstring.
> Add to_svg for graphs

- mathics/builtin/drawing/graphics3d.py
Solve [the problem mentioned here](https://github.com/Mathics3/mathics-django/pull/74#issuecomment-860109856).
> Change double quote to single quote

- mathics/builtin/graphics.py
- mathics/formatter/svg.py
This branch fix the position and opacity of the tick numbers in charts.
> Fix tick numbers in charts

- mathics/doc/tex/Makefile
- mathics/doc/tex/mathics.tex
> run latexmk in verbose mode; Nuke roman numerals

- mathics/formatter/svg.py
@rocky this fix the vertical align of the tick numbers (the other PR fixed the horizontal align).
> Improve tick numbers in charts

- mathics/builtin/assignment.py
- mathics/doc/__init__.py
- mathics/doc/common_doc.py
- mathics/docpipeline.py
Don't print modules which would create sections or chapters.
Move mathics.doc.doc to mathics.doc.common_doc
> Miscellaneous documentation code fixes

- mathics/format/svg.py
> Fix charts tick number

- mathics/__init__.py
- mathics/autoload/settings.m
- mathics/core/definitions.py
- test/test_settings.py
Remove System`$Notebooks from settings.m as all front ends already implement it
> Remove System`$Notebooks from settings.m

- CHANGES.rst
- MANIFEST.in
- requirements-dev.txt
- setup.py
The next release this should address #1452
> Add requirements-*.txt files to distribution

- mathics/format/asy.py
And it looks like there was a bug to me for:
Graphics3D[Arrow[{{1, 1, -1}, {2, 2, 0}, {3, 3, -1}, {4, 4, 0}}]] // TeXForm
> Reorganize Arrow3D a little.

- Makefile
- mathics/builtin/datentime.py
- mathics/doc/common_doc.py
- mathics/doc/tex/Makefile
- mathics/doc/tex/doc2latex.py
- mathics/docpipeline.py
> Split out Pickle to LaTeX file creation and

- mathics/builtin/arithfns/basic.py
- mathics/builtin/assignment.py
- mathics/builtin/strings.py
- mathics/doc/__init__.py
- mathics/doc/common_doc.py
- mathics/doc/tex/doc2latex.py
- mathics/docpipeline.py
- mathics/settings.py
Bang on getting sections under guide sections in LaTeX document.
> Fix subsectioning in producing LaTeX, refactor, and improve code and testing

- mathics/builtin/drawing/image.py
> Decode encoded image source

- mathics/builtin/box/graphics3d.py
A change in mathics-threejs-backend needs to be done in parallel to this.
> Remove viewpoint rescale

- mathics/builtin/box/graphics3d.py
- mathics/format/svg.py
We still need to release mathics-threejs-backend 0.5.0.
> Add mathics-threejs-backend version

- mathics/builtin/arithfns/basic.py
- mathics/builtin/datentime.py
- mathics/builtin/list/associations.py
This is used in Mathics Djano when showing subsection lists in a section
> Start adding builtin summary texts

- mathics/builtin/optiondoc.py
- mathics/doc/tex/README.rst
- mathics/doc/tex/latexmkrc
On filling sine waves (Axes, ListLinePlot go adjust stepsize 0.5 -> 0.2.
Document latexmkrc and have it check Ghostview and Asymptote versions
> Small LaTeX doc fixes

- mathics/builtin/drawing/graphics3d.py
- mathics/builtin/list/constructing.py
Small changes to improve documentation and layout.
Also stricter signature checking on cylinder.
> Graphics3D doc and format tweaks

- mathics/builtin/drawing/graphics3d.py
> Map `Cuboid` with 2d coordinates to `Rectangle`

- mathics/builtin/arithmetic.py
- mathics/builtin/specialfns/bessel.py
Expand _MPMathMultiFunction to handle a function which is sympy only but
not mpmath.
> Make a pass over besself fns

- mathics/settings.py
DOC_USER_TEX_DATA_PATH
DOC_SYSTEM_TEX_DATA_PATH
APPDATA
> Alllow ENV settings for DOC paths

- mathics/doc/common_doc.py
- mathics/doc/tex/doc2latex.py
- mathics/doc/tex/mathics.tex
Add ability to print only chapters or parts of a manual
Use smaller font in title for Mathics release number
> Useful LaTeX doc tweaks

- CHANGES.rst
- mathics/autoload/rules/GudermannianRules.m
- test/test_gudermannian.py
> Add GudermannianRules

- mathics/doc/common_doc.py
- mathics/doc/tex/doc2latex.py
Builds on what we did before in order to filter by chapter and part.
This now gives a us a good ability to QUICKLY iterate over problems in making the doc or in asymptote problems.
> Add ability to filter doc making by section

- CHANGES.rst
- mathics/builtin/drawing/splines.py
- mathics/format/asy.py
Add summary text for all splines.
> BezierCurve for Asy is closer to MMA spec

- mathics/builtin/box/graphics3d.py
- mathics/format/json.py
The next is work in uniform polyhedra!
About `to_json`: now it is in its own file instead of the 3d box class, it happens for all primitives, so there is no why to check if the convert function is inexistent.
> More cleaning

- mathics/builtin/box/uniform_polyhedra.py
- mathics/builtin/drawing/uniform_polyhedra.py
- mathics/format/json.py
> Do this wok

- CHANGES.rst
- mathics/builtin/box/graphics3d.py
- mathics/builtin/box/uniform_polyhedra.py
- mathics/builtin/drawing/graphics3d.py
- mathics/builtin/drawing/uniform_polyhedra.py
- mathics/builtin/graphics.py
- mathics/format/json.py
Work remains to sets center point and "radius".
Also, UniformPolyhedron doesn't take the above parameters directly while  the named versions, e.g. Octahedron do allow these parameters - work out how we want to represent this then.
> UniformPolyhedra

- mathics/builtin/drawing/__init__.py
- mathics/builtin/drawing/graphics_internals.py
- mathics/builtin/drawing/image.py
- mathics/builtin/drawing/image_internals.py
Other small changes to wording.
> Mark modules that don't get documented.

- mathics/builtin/comparison.py
- mathics/builtin/numeric.py
See https://mathematica.stackexchange.com/questions/253637/how-to-think-about-the-answer-to-rationlize-11-5-1
Fixes #1553
> Symmetric Rationalize

- CHANGES.rst
- mathics/autoload/formats/JSON/Import.m
- mathics/builtin/fileformats/htmlformat.py
- mathics/builtin/fileformats/xmlformat.py
- mathics/builtin/files_io/files.py
- mathics/builtin/files_io/filesystem.py
- mathics/builtin/files_io/importexport.py
- mathics/core/read.py
- mathics/core/streams.py
- test/test_importexport.py
This is a rebase of some old code. I got maybe 80% of the way a while ago. But  this is still needed. 
Start at `py.test test/test_importexport.py`
and `fix read_in_stream()`
> Read list refactor

- mathics/builtin/arithmetic.py
- mathics/builtin/drawing/image.py
- mathics/builtin/files_io/filesystem.py
- mathics/builtin/inout.py
- mathics/builtin/intfns/combinatorial.py
- mathics/builtin/list/eol.py
- mathics/builtin/lists.py
- mathics/builtin/numbers/numbertheory.py
- mathics/builtin/numbers/randomnumbers.py
- mathics/builtin/optimization.py
- mathics/builtin/physchemdata.py
- mathics/builtin/quantities.py
- mathics/builtin/string/characters.py
- mathics/builtin/system.py
> Replace `_?TypeQ` by `_Type`

- mathics/builtin/arithfns/basic.py
- mathics/builtin/arithmetic.py
- mathics/builtin/datentime.py
- mathics/builtin/drawing/graphics3d.py
- mathics/builtin/files_io/files.py
- mathics/builtin/files_io/filesystem.py
- mathics/builtin/options.py
I don't know why the difference is so big, but...
> Small tweaks

- mathics/builtin/drawing/graphics3d.py
I was searching for methods with too much applies and I remebered of this.
> Fix 2d cuboid

- mathics/builtin/drawing/image.py
- mathics/builtin/numbers/numbertheory.py
- mathics/builtin/patterns.py
- mathics/builtin/physchemdata.py
Pattern-matching signature changes for NextPrime and ElementData
See https://github.com/mathics/Mathics/pull/1567 for details.
> Quickpatterntest

- mathics/builtin/arithfns/basic.py
- mathics/builtin/arithmetic.py
- mathics/builtin/drawing/uniform_polyhedra.py
- mathics/builtin/lists.py
- mathics/builtin/numbers/algebra.py
- mathics/builtin/numbers/numbertheory.py
Last small tweaks at least for the next week.
I'll update mathics-benchmark so it breaks the query into multiple lines every x characters.
> Small performance improvements though rule rewriting

- mathics/builtin/inout.py
> Improve MakeBoxes performance by rewriting some rules
